# **importing the needed libraries**

In [ ]:
!pip install numpy==1.25.2

Requirement already satisfied: numpy==1.25.2 in /usr/local/lib/python3.11/dist-packages (1.25.2)

In [ ]:
!pip install gensim

Requirement already satisfied: gensim in /usr/local/lib/python3.11/dist-packages (4.3.3)
Requirement already satisfied: numpy<2.0,>=1.18.5 in /usr/local/lib/python3.11/dist-packages (from gensim) (1.25.2)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from gensim) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim) (7.1.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim) (1.17.2)

In [ ]:
pip install fasttext

Collecting fasttext
  Downloading fasttext-0.9.3.tar.gz (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 6.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pybind11>=2.2 (from fasttext)
  Using cached pybind11-2.13.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: setuptools>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from fasttext) (75.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from fasttext) (1.25.2)
Using cached pybind11-2.13.6-py3-none-any.whl (243 kB)
Building wheels for collected packages: fasttext
  Building wheel for fasttext (pyproject.toml) ... done
  Created wheel for fasttext: filename=fasttext-0.9.3-cp311-cp311-linux_x86_64.whl size=4313509 sha256=833c9038bc97a686c4860787a5156323c84028d07a878c5e9b0075bc296cbb65
  Stored in directory: /root/.cache/pip/wheels/65/4f/35/5057db0249224e9ab55a513fa6b79451473ceb7713017823c3
Successfully built fasttext
Installing collected packages: pybind11, fasttext
Successfully installed fasttext-0.9.3 pybind11-2.13.6

In [ ]:
import re
import nltk
import string
import numpy as np
import pandas as pd
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.stem.isri import ISRIStemmer
from sklearn.feature_extraction.text import CountVectorizer
from gensim.models import Word2Vec
from gensim.models import FastText
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
import fasttext
from sklearn.model_selection import train_test_split

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
!pip install camel-tools[full]

Collecting camel-tools[full]
  Downloading camel_tools-1.5.6-py3-none-any.whl.metadata (10 kB)
WARNING: camel-tools 1.5.6 does not provide the extra 'full'
Requirement already satisfied: future in /usr/local/lib/python3.11/dist-packages (from camel-tools[full]) (1.0.0)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from camel-tools[full]) (1.17.0)
Collecting docopt (from camel-tools[full])
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cachetools in /usr/local/lib/python3.11/dist-packages (from camel-tools[full]) (5.5.2)
Requirement already satisfied: numpy<2 in /usr/local/lib/python3.11/dist-packages (from camel-tools[full]) (1.25.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from camel-tools[full]) (1.13.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from camel-tools[full]) (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from camel-tools[full]) (1.6.1)
Requirement already satisfied: dill in /usr/local/lib/python3.11/dist-packages (from camel-tools[full]) (0.3.7)
Requirement already satisfied: torch>=2.0 in /usr/local/lib/python3.11/dist-packages (from camel-tools[full]) (2.6.0+cu124)
Collecting transformers<4.44.0,>=4.0 (from camel-tools[full])
  Downloading transformers-4.43.4-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 3.9 MB/s eta 0:00:00
Requirement already satisfied: editdistance in /usr/local/lib/python3.11/dist-packages (from camel-tools[full]) (0.8.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from camel-tools[full]) (2.32.3)
Collecting emoji (from camel-tools[full])
  Downloading emoji-2.14.1-py3-none-any.whl.metadata (5.7 kB)
Collecting pyrsistent (from camel-tools[full])
  Downloading pyrsistent-0.20.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Requirement already satisfied: tabulate in /usr/local/lib/python3.11/dist-packages (from camel-tools[full]) (0.9.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from camel-tools[full]) (4.67.1)
Collecting muddler (from camel-tools[full])
  Downloading muddler-0.1.3-py3-none-any.whl.metadata (7.5 kB)
Collecting camel-kenlm>=2025.4.8 (from camel-tools[full])
  Downloading camel-kenlm-2025.4.8.zip (556 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 556.5/556.5 kB 43.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[full]) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[full]) (4.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[full]) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[full]) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[full]) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=2.0->camel-tools[full])
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=2.0->camel-tools[full])
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=2.0->camel-tools[full])
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=2.0->camel-tools[full])
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=2.0->camel-tools[full])
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=2.0->camel-tools[full])
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=2.0->camel-tools[full])
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=2.0->camel-tools[full])
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=2.0->camel-tools[full])
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[full]) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[full]) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[full]) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=2.0->camel-tools[full])
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[full]) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[full]) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=2.0->camel-tools[full]) (1.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.11/dist-packages (from transformers<4.44.0,>=4.0->camel-tools[full]) (0.32.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers<4.44.0,>=4.0->camel-tools[full]) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers<4.44.0,>=4.0->camel-tools[full]) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<4.44.0,>=4.0->camel-tools[full]) (2024.11.6)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers<4.44.0,>=4.0->camel-tools[full]) (0.5.3)
Collecting tokenizers<0.20,>=0.19 (from transformers<4.44.0,>=4.0->camel-tools[full])
  Downloading tokenizers-0.19.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->camel-tools[full]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->camel-tools[full]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->camel-tools[full]) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->camel-tools[full]) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->camel-tools[full]) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->camel-tools[full]) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->camel-tools[full]) (2025.4.26)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->camel-tools[full]) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->camel-tools[full]) (3.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers<4.44.0,>=4.0->camel-tools[full]) (1.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=2.0->camel-tools[full]) (3.0.2)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.7 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 130.5 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 105.5 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 63.2 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.7 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 11.6 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 43.0 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 19.6 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 3.3 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 109.6 MB/s eta 0:00:00
Downloading transformers-4.43.4-py3-none-any.whl (9.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/9.4 MB 134.4 MB/s eta 0:00:00
Downloading camel_tools-1.5.6-py3-none-any.whl (124 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.7/124.7 kB 14.4 MB/s eta 0:00:00
Downloading emoji-2.14.1-py3-none-any.whl (590 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 590.6/590.6 kB 50.1 MB/s eta 0:00:00
Downloading muddler-0.1.3-py3-none-any.whl (16 kB)
Downloading pyrsistent-0.20.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (120 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.0/120.0 kB 13.4 MB/s eta 0:00:00
Downloading tokenizers-0.19.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 111.7 MB/s eta 0:00:00
Building wheels for collected packages: camel-kenlm, docopt
  Building wheel for camel-kenlm (pyproject.toml) ... done
  Created wheel for camel-kenlm: filename=camel_kenlm-2025.4.8-cp311-cp311-linux_x86_64.whl size=3455561 sha256=0224242da99eb446a5cf3993f0dd2dd1c377de31d8e1350f76b774509fcc233b
  Stored in directory: /root/.cache/pip/wheels/19/b9/62/8559aee1915ae6690fcc902a972a9ba0ff46d3ee67fea2aa44
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=df59f47358b9c53c68512e3b9a454a1091b143f95fceea8342bbf58d795d40c5
  Stored in directory: /root/.cache/pip/wheels/1a/b0/8c/4b75c4116c31f83c8f9f047231251e13cc74481cca4a78a9ce
Successfully built camel-kenlm docopt
Installing collected packages: docopt, camel-kenlm, pyrsistent, nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, muddler, emoji, nvidia-cusparse-cu12, nvidia-cudnn-cu12, tokenizers, nvidia-cusolver-cu12, transformers, camel-tools
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.21.1
    Uninstalling tokenizers-0.21.1:
      Successfully uninstalled tokenizers-0.21.1
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
  Attempting uninstall: transformers
    Found existing installation: transformers 4.52.4
    Uninstalling transformers-4.52.4:
      Successfully uninstalled transformers-4.52.4
Successfully installed camel-kenlm-2025.4.8 camel-tools-1.5.6 docopt-0.6.2 emoji-2.14.1 muddler-0.1.3 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 pyrsistent-0.20.0 tokenizers-0.19.1 transformers-4.43.4

# **importing the dataset**

In [ ]:
patient_dr = pd.read_csv("/content/altibbi_specialty_data.csv")

In [ ]:
patient_dr.head()

,specialty_id,name_ar,question_body
0,23,طب عيون,استشاره عيون
1,14,جراحة العظام والمفاصل,السلام عليكم ممكن دكتور مفاصل واعصاب
2,14,جراحة العظام والمفاصل,عندي نقص فيتامين د هل ممكن استخدم معه كالسيوم
3,23,طب عيون,عمليه الحول للكبار
4,14,جراحة العظام والمفاصل,ألم بالكتف الايسر من فترة

In [ ]:
#the data is big so we took 25000 random samples of it
df = patient_dr.drop("name_ar", axis=1)
df = df.sample(n=25000, random_state=42)

In [ ]:
df.head()

       specialty_id                                      question_body
86128            91                                أريد التحدث مع طبيب
60680            25                                          فيني سمنه
73441            25                               اريد نظام رجيم مناسب
45872            23                                         صداع غثيان
86440            14  الم شديد جداً في فالجنب الايسر من الظهر من ٥ ا...

# **Pre-processing**

***Pre-processing using Iris stemming (NLTK)***

In [ ]:
def preprocessing_patient_stemming(patient_Question):
    # setting a standard
    patient_Question = re.sub(r'[إأآ]', 'ا', patient_Question)
    patient_Question = re.sub(r'ؤ', 'و', patient_Question)
    patient_Question = re.sub(r'ئ', 'ي', patient_Question)
    patient_Question = re.sub(r'ء', '', patient_Question)
    patient_Question = re.sub(r'ة', 'ه', patient_Question)
    # removing harkat
    patient_Question = re.sub(r'[\u064B-\u0652]', '', patient_Question)
    # Removing punctuation
    patient_Question = re.sub(r'[^\w\s]', ' ', patient_Question)
    # tokenization
    tokens = nltk.word_tokenize(patient_Question)
    # Remove stopwords
    ar_stopwords = set(stopwords.words('arabic'))
    without_stop = [word for word in tokens if word not in ar_stopwords]
    # stemming
    stemmer = ISRIStemmer()
    steammed = [stemmer.stem(word) for word in without_stop]
    return steammed

In [ ]:
preprocessed_Question_Stemming = [preprocessing_patient_stemming(text) for text in df['question_body']]

In [ ]:
for question, processed_qu in list(zip(df['question_body'], preprocessed_Question_Stemming))[:100]:
    print(f" Question: {question}")
    print(f" Processed Question: {processed_qu}\n")

 Question: أريد التحدث مع طبيب
 Processed Question: ['ارد', 'حدث', 'طبب']

 Question: فيني سمنه
 Processed Question: ['فين', 'سمن']

 Question: اريد نظام رجيم مناسب
 Processed Question: ['ارد', 'نظم', 'رجم', 'نسب']

 Question: صداع غثيان
 Processed Question: ['صدع', 'غثي']

 Question: الم شديد جداً في فالجنب الايسر من الظهر من ٥ ايام مايفك ولاثانيه مع عدم القدره ع المشي والحركه والنوم رغم المسكنات
 Processed Question: ['الم', 'شدد', 'جدا', 'جنب', 'يسر', 'ظهر', '٥', 'ايم', 'ايف', 'ولاثانيه', 'عدم', 'قدر', 'مشي', 'حرك', 'نوم', 'رغم', 'سكن']

 Question: كيف ازيد طولي ماهو الشي الدي نعمله من شأن يزيد الطول
 Processed Question: ['ازد', 'طول', 'اهو', 'الش', 'الد', 'عمل', 'شان', 'يزد', 'طول']

 Question: اعاني من القرنية المخروطية ولقد عملت عملية تثبيت للقرنية منذ ٣ سنوات ونجحت هل يمكنني الان عمل عملية ليزك لتصحيح بصري وترك النظارات؟
 Processed Question: ['اعا', 'قرن', 'خرط', 'لقد', 'عمل', 'عمل', 'ثبت', 'قرن', '٣', 'سنو', 'نجح', 'يمك', 'الن', 'عمل', 'عمل', 'ليز', 'صحح', 'بصر', 'وتر', 'نظر']

 Question: نزول كتل دم اثناء الدورة الشهرية
 Processed Question: ['نزل', 'كتل', 'دم', 'دور', 'شهر']

 Question: بنتي عمره شهرين ونص وكالوا احتمال عنده خلع ولادي تبقه من تكبر تعرج حتى لو تعالج
 Processed Question: ['بنت', 'عمر', 'شهر', 'ونص', 'وكل', 'حمل', 'عند', 'خلع', 'ولد', 'تبق', 'كبر', 'عرج', 'علج']

 Question: الم اسفل الظهر
 Processed Question: ['الم', 'سفل', 'ظهر']

 Question: احمرار بالعينين مع افرازات، وانتفاخ بالجفن، وألم عند ضغطها ، وصداع.
 Processed Question: ['حمرار', 'عين', 'فرز', 'نفخ', 'جفن', 'ولم', 'ضغط', 'صدع']

 Question: طفلي عمر السنتين كان حولين عيونه حبوب ومحمره والان داخل العين حمراء
 Processed Question: ['طفل', 'عمر', 'سنت', 'حول', 'عين', 'حبب', 'حمر', 'وال', 'دخل', 'عين', 'حمر']

 Question: تناول الفيتامينات مع بعضها
 Processed Question: ['نول', 'يتم', 'بعض']

 Question: وجود مشاكل في النظام ونزول في الوزن
 Processed Question: ['وجد', 'شكل', 'نظم', 'نزل', 'وزن']

 Question: نعم اريد طيب جراحه عظام
 Processed Question: ['ارد', 'طيب', 'جرح', 'عظم']

 Question: اعاني من دمامل صغيرة في الثدي ظهرت لي بعد زيادة في الوزن هل السمنه هي السبب؟
 Processed Question: ['اعا', 'دممل', 'صغر', 'ثدي', 'ظهر', 'زيد', 'وزن', 'سمن', 'سبب']

 Question: السلام عليكم دكتور عندي بقع صفرا ف بياض العين خقي ماادري من ايش
 Processed Question: ['سلم', 'علي', 'دكتور', 'عند', 'بقع', 'صفر', 'بيض', 'عين', 'خقي', 'ادر', 'ايش']

 Question: الم شديد بالاسنان نتيجه نحت ضرس وبمجرد ماينتهي مفعول البنادول يرجع الالم
 Processed Question: ['الم', 'شدد', 'اسن', 'نتج', 'نحت', 'ضرس', 'جرد', 'اين', 'فعل', 'ندل', 'رجع', 'الم']

 Question: الم بالكتف
 Processed Question: ['الم', 'كتف']

 Question: زيادة هرمون الاستروجين
 Processed Question: ['زيد', 'هرم', 'روج']

 Question: السمنه اريد الحصول على افضل حبوب انقاص الوزن
 Processed Question: ['سمن', 'ارد', 'حصل', 'فضل', 'حبب', 'قاص', 'وزن']

 Question: ممكن استخدم الدواء FAST LOSE مع العلم استخدم مكملات غذائيه مثل فيتامين د و ب و اوميقا ثري مع العلم وزني ١٢٥ وعمري ٢٧ هل له اثار جانبية وهل هو امن ؟
 Processed Question: ['مكن', 'خدم', 'دوا', 'FAST', 'LOSE', 'علم', 'خدم', 'كمل', 'غذي', 'يتم', 'ومق', 'ثري', 'علم', 'وزن', '١٢٥', 'عمر', '٢٧', 'اثر', 'جنب', 'وهل', 'امن']

 Question: التهاب العين
 Processed Question: ['تهب', 'عين']

 Question: بنتي عمرها ٨ سنوات صارت مره نفسيه مو عارفه اتعامل معاها
 Processed Question: ['بنت', 'عمر', '٨', 'سنو', 'صرت', 'مره', 'نفس', 'مو', 'عرف', 'عمل', 'معا']

 Question: مفصل القدم
 Processed Question: ['فصل', 'قدم']

 Question: عاوز اترك العاده ١٧ سنه
 Processed Question: ['عوز', 'اتر', 'عده', '١٧', 'سنه']

 Question: الم في الركبه
 Processed Question: ['الم', 'ركب']

 Question: انا عندي تكيسات ووزني زايد وزني 90
 Processed Question: ['انا', 'عند', 'تكس', 'ووز', 'زيد', 'وزن', '90']

 Question: لدي الم ركبة عند ثني الركبة على أثر وقعة يمتد أحياناً أسفل أو فوق الركبة الالم غير ثابت انا في بلد الطبابة فيه مكلفة وليس لدي تأمين أرجو المساعدة
 Processed Question: ['لدي', 'الم', 'ركب', 'ثني', 'ركب', 'اثر', 'وقع', 'متد', 'احا', 'سفل', 'او', 'ركب', 'الم', 'ثبت', 'انا', 'بلد', 'طبب', 'كلف', 'وليس', 'لدي', 'تام', 'رجو', 'سعد']

 Question: الالم في الجزء الأيسر العلوي من الثدي الايمن عند حركه الجسم للامام أو تحريك الكتف وعدم وجود أي تغير في شكل الثدي أو أي إفرازات أو أي عقد في أي منطقه سني ٢٠ سنه
 Processed Question: ['الم', 'لجز', 'يسر', 'علي', 'ثدي', 'ايم', 'حرك', 'جسم', 'امم', 'او', 'حرك', 'كتف', 'عدم', 'وجد', 'اي', 'تغر', 'شكل', 'ثدي', 'او', 'اي', 'فرز', 'او', 'اي', 'عقد', 'اي', 'طقه', 'سني', '٢٠', 'سنه']

 Question: اريد ان استشير كيف انزل وزني وخاصه البطن
 Processed Question: ['ارد', 'ان', 'شير', 'نزل', 'وزن', 'وخص', 'بطن']

 Question: مرحبا دكتور زوجي اقفل باب السياره على اصبعه من اسبوعين وراح المستشفى وتاكد انه مافي كسر ولكن مايزال الاصبع متورم وفيه دم اسود ايش الحل
 Processed Question: ['رحب', 'دكتور', 'زوج', 'قفل', 'باب', 'سير', 'صبع', 'سبع', 'ورح', 'شفى', 'تكد', 'انه', 'افي', 'كسر', 'مايزال', 'صبع', 'تورم', 'وفه', 'دم', 'اسد', 'ايش', 'لحل']

 Question: بياض لسان يشبه الفرو
 Processed Question: ['بيض', 'لسن', 'يشب', 'فرو']

 Question: حبه في جفن عيني من الداخل
 Processed Question: ['حبه', 'جفن', 'عين', 'دخل']

 Question: طبيبه نساء اعاني من اعراض البرد من دوخه واستفراغ وغثيان
 Processed Question: ['طبب', 'نسا', 'اعا', 'عرض', 'برد', 'دوخ', 'واستفراغ', 'وغث']

 Question: السلام عليكم ورحمة الله لدي مشكلة نفسية (الرهاب الاجتماعي) منذ أكثر من ١٠ سنوات، بسبب موقف محرج حدث لي، أحتاج من يساعدني
 Processed Question: ['سلم', 'علي', 'رحم', 'الل', 'لدي', 'شكل', 'نفس', 'رهب', 'جمع', 'كثر', '١٠', 'سنو', 'سبب', 'وقف', 'حرج', 'حدث', 'حاج', 'سعد']

 Question: ١-ازيثرومايسين مضاد عن العدوى البكتيريه ولعلاج اثار كورونا ! ٢-تيليفاست مضاد الهستامين ٣-توبريكس عن التهاب الملتحمه والقرنيه دكتور تشرحلي ليش رقم ١ !؟
 Processed Question: ['١', 'ازيثرومايس', 'ضاد', 'عدى', 'كتر', 'علج', 'اثر', 'كورو', '٢', 'تيليفاست', 'ضاد', 'هستام', '٣', 'ريكس', 'تهب', 'لحم', 'قرن', 'دكتور', 'شرحل', 'ليش', 'رقم', '١']

 Question: انا حصلت عندي ضربة في المرفق وانا اخذ شاور وكانت ضربة قوية ضربت في عمود حديدي " لتعليق المناشف " من بعد ذلك والمرفق انزاح من مكانه ويصدر اصوات طقطقه.
 Processed Question: ['انا', 'حصل', 'عند', 'ضرب', 'رفق', 'ونا', 'اخذ', 'شور', 'وكانت', 'ضرب', 'قوه', 'ضرب', 'عمد', 'حدد', 'علق', 'نشف', 'رفق', 'زاح', 'كنه', 'صدر', 'اصو', 'طقطق']

 Question: مشكلة لدى والدي عمره ٥٩ سنة - يوجد عنده خشونه في الركبة و التهاب يعاني الان من الاآم في الركبة و يوجد تخشب في الاطراف مع العلم يعاني من مرض السكر
 Processed Question: ['شكل', 'ولد', 'عمر', '٥٩', 'سنه', 'وجد', 'عند', 'خشن', 'ركب', 'تهب', 'يعا', 'الن', 'اام', 'ركب', 'وجد', 'خشب', 'طرف', 'علم', 'يعا', 'مرض', 'سكر']

 Question: السلام عليكم ابنتي حفرة قدمها مائل قليلا الطبيب شك انه خلع ولاده وصورت اليوم تصوير تلفزيوني
 Processed Question: ['سلم', 'علي', 'ابن', 'حفر', 'قدم', 'ايل', 'قلل', 'طبب', 'شك', 'انه', 'خلع', 'ولد', 'وصر', 'اليوم', 'صور', 'فزو']

 Question: السلام عليكم دكتور هذا حال اظافر رجلي بالذات الظفر الكبير قبل طلعلي ظفر غائر وعانيت وعالجت بعدها عرفت كيف اقص اظافري من بعدها صارت اظافري كذا لست اعلم
 Processed Question: ['سلم', 'علي', 'دكتور', 'حال', 'ظفر', 'رجل', 'ذات', 'ظفر', 'كبر', 'طلعل', 'ظفر', 'غير', 'وعن', 'علج', 'بعد', 'عرف', 'اقص', 'ظفر', 'بعد', 'صرت', 'ظفر', 'علم']

 Question: ابني عنيف في بعض الاحيان ومشاغب و بيعمل سلوكيات خاطئه
 Processed Question: ['ابن', 'عنف', 'احي', 'شغب', 'عمل', 'سلك', 'خطي']

 Question: ظهري يؤلمني من لوح الكتف وبينزل الوجع لتحت
 Processed Question: ['ظهر', 'ولم', 'لوح', 'كتف', 'نزل', 'وجع', 'لتح']

 Question: مشكله بروز الفك العلوي
 Processed Question: ['شكل', 'برز', 'الف', 'علي']

 Question: السلام عليكم انا عندي تقوس في الرجل وش الحل ؟
 Processed Question: ['سلم', 'علي', 'انا', 'عند', 'تقس', 'رجل', 'وش', 'لحل']

 Question: ابني عمره ٨ سنوات عنده شعور الرغبه بأكل شعر الرأس لاكنه لايفعل وسبب له توتر
 Processed Question: ['ابن', 'عمر', '٨', 'سنو', 'عند', 'شعر', 'رغب', 'بكل', 'شعر', 'راس', 'لكن', 'فعل', 'سبب', 'وتر']

 Question: عن العظام
 Processed Question: ['عظم']

 Question: تمنيل اطرافي
 Processed Question: ['منل', 'طرف']

 Question: في حاجه دخلت عيني او جرحتها بالغلط وهي مره قاعده تعورني مو قادره افتحها
 Processed Question: ['حجه', 'دخل', 'عين', 'او', 'جرح', 'غلط', 'وهي', 'مره', 'قعد', 'تعر', 'مو', 'قدر', 'فتح']

 Question: بعاني من النحافه وأخذت ترياكتين لمده ٣ ايام وبعدين بطلت ورجعت بعد شهرين اخدت عشرين يوم مواصلين وبعدين بطلت تاني اخدت شوكلاته لزياده الحديد ومفيش فايد
 Processed Question: ['بعا', 'نحف', 'وخذ', 'ترا', 'لمد', '٣', 'ايم', 'بعد', 'بطل', 'رجع', 'شهر', 'اخد', 'يوم', 'وصل', 'بعد', 'بطل', 'تني', 'اخد', 'شوكل', 'زيد', 'حدد', 'فيش', 'فيد']

 Question: عندي رتباك عند فعل اي شيء امام الآخرين ...مع تحرك الاطراف
 Processed Question: ['عند', 'رتب', 'فعل', 'اي', 'شي', 'امم', 'اخر', 'تحر', 'طرف']

 Question: نزعت عصب ونظفت خراج وحطيت حشوه مؤقته وتسبب لي الخراج بتورم شديد وتنمل بالوجه واليوم طلع لي هذا باللثه وش السبب؟؟؟
 Processed Question: ['نزع', 'عصب', 'نظف', 'خرج', 'وحط', 'حشه', 'وقت', 'سبب', 'خرج', 'ورم', 'شدد', 'نمل', 'وجه', 'يوم', 'طلع', 'لثه', 'وش', 'سبب']

 Question: استشاري عظام
 Processed Question: ['شار', 'عظم']

 Question: الام الضرس
 Processed Question: ['الم', 'ضرس']

 Question: Tawuniya اشعر بالم شديد في الفك هل يوجد حل مؤقت لتسكين الالم مثل الكمادات مثلا او شي اخر؟
 Processed Question: ['Tawuniya', 'شعر', 'بلم', 'شدد', 'الف', 'وجد', 'حل', 'وقت', 'لتس', 'الم', 'كمد', 'ثلا', 'او', 'شي', 'اخر']

 Question: كنت بتكلم عادى مع الصيدليى يوم الخميس دخت ووقعت ومناخيرى وبقى اتفتحوا قسلى الضغط واطى جدا بعد كده الجمعة ورم فى بقى السبت فى مناخيرى الاحد فى عينى
 Processed Question: ['كنت', 'كلم', 'عدى', 'صيدليى', 'يوم', 'خمس', 'دخت', 'وقع', 'ومناخيرى', 'بقى', 'فتح', 'قسلى', 'ضغط', 'وطى', 'جدا', 'كده', 'جمع', 'ورم', 'فى', 'بقى', 'سبت', 'فى', 'مناخيرى', 'احد', 'فى', 'عينى']

 Question: أعاني من مرض في الشبكية وأنا الآم لي أسبوعين تقريبًا صرت أشوف زي النور الابيض المتقطع في جانب عيني ولا أدري ايش هذا النور وايش سببه
 Processed Question: ['اعا', 'مرض', 'شبك', 'ونا', 'الم', 'سبع', 'قرب', 'صرت', 'اشف', 'زي', 'نور', 'ابض', 'تقطع', 'جنب', 'عين', 'ادر', 'ايش', 'نور', 'ويش', 'سبب']

 Question: زوجتي ٣٠ عاما تعاني من الم ف الكتف الايسر وتحت الكتف قليلا من الامام والخلف واحيانا تشعر بسخونة ف نفس المكان ولكن الالم غير مستمر
 Processed Question: ['زوج', '٣٠', 'عما', 'تعا', 'الم', 'كتف', 'يسر', 'وتح', 'كتف', 'قلل', 'امم', 'خلف', 'وحي', 'شعر', 'سخو', 'كان', 'الم', 'سمر']

 Question: عندي الم في رجلي اليمنى من اعلى الفخذ لاخر الساق وقت النوم ويزيد مع البرد لدرجة يمنعني من النوم مستمر الالم من سنين وما احس فيه باقي اليوم
 Processed Question: ['عند', 'الم', 'رجل', 'منى', 'على', 'فخذ', 'لخر', 'ساق', 'وقت', 'نوم', 'يزد', 'برد', 'درج', 'منع', 'نوم', 'سمر', 'الم', 'سنن', 'احس', 'بقي', 'اليوم']

 Question: مرحبا قدمي تورمت قليلا لانها انصدمت بكرسي حديد
 Processed Question: ['رحب', 'قدم', 'ورم', 'قلل', 'لان', 'صدم', 'كرس', 'حدد']

 Question: اعاني من زياده الوزن
 Processed Question: ['اعا', 'زيد', 'وزن']

 Question: بضغض على اسنانى منذ حوالي اربع ايام
 Processed Question: ['ضغض', 'ننى', 'حلي', 'ربع', 'ايم']

 Question: الم في الكعب الرجل
 Processed Question: ['الم', 'كعب', 'رجل']

 Question: عملت سحب عصب للاسنان قبل اسبوع لابني والى الان يعاني من الن قوي حتى بغد اخذ المسكن
 Processed Question: ['عمل', 'سحب', 'عصب', 'اسن', 'سبع', 'لاب', 'ولى', 'الن', 'يعا', 'الن', 'قوي', 'بغد', 'اخذ', 'سكن']

 Question: ارجوشاكرامساعدتي في تحديد المرض الذي اعاني منه في مفصل الركبه اليسرى خلال الأسبوعين الماضيين  اضافة الى ظهور تورم حول مفصل الركبه ويمتد الى اسفل القدم
 Processed Question: ['ارجوشاكرامساعدتي', 'حدد', 'مرض', 'اعا', 'فصل', 'ركب', 'سرى', 'خلل', 'سبع', 'اضي', 'ضفه', 'الى', 'ظهر', 'ورم', 'حول', 'فصل', 'ركب', 'متد', 'الى', 'سفل', 'قدم']

 Question: خدش بالقرنيه
 Processed Question: ['خدش', 'قرن']

 Question: ابه أستشير دكتور مكالمه استشاره عن علاج
 Processed Question: ['ابه', 'شير', 'دكتور', 'كلم', 'شار', 'علج']

 Question: زوجي كان مستمر على ادوية الاكتئاب 3 سنين وتركها فجاءه بعدها بشهرين سائت حالته يشعر بدوخه وكهربا بالراس والم بالعظام واكتئاب وحاول الرجوع شهر وماكان لهامفعول وتركها الان ماهو الحل هل الرجوع لها هو الحل
 Processed Question: ['زوج', 'سمر', 'ادي', 'كيب', '3', 'سنن', 'وتر', 'فجه', 'بعد', 'شهر', 'سيت', 'حلت', 'شعر', 'بدخ', 'كهرب', 'راس', 'ولم', 'عظم', 'كيب', 'حول', 'رجع', 'شهر', 'ومك', 'لهامفعول', 'وتر', 'الن', 'اهو', 'لحل', 'رجع', 'لحل']

 Question: هل هنالك مخاطر عند استعمال المكمل الغذائي ‏Centrum-سينتروم
 Processed Question: ['خطر', 'عمل', 'كمل', 'غذي', 'Centrum', 'ترم']

 Question: مرحبا بنتي عمرها ١٠ شهور ونص ولسى م تحبي بس تزحف واذا وقفتها رجلها اليسرى ترفعها هذي صور الاشعه
 Processed Question: ['رحب', 'بنت', 'عمر', '١٠', 'شهر', 'ونص', 'لسى', 'تحب', 'زحف', 'وذا', 'وقف', 'رجل', 'سرى', 'رفع', 'صور', 'اشع']

 Question: زوجتي حامل في الشهر الخامس وبسبب حملها لغرض ما بيدها وبطريقة خاطئة تعرض ذراعها الايسر الى الم شديد لا تستطيع النوم بسبب الالم فما هوا الحل من فضلكم
 Processed Question: ['زوج', 'حمل', 'شهر', 'خمس', 'سبب', 'حمل', 'غرض', 'بيد', 'طرق', 'خطي', 'عرض', 'ذرع', 'يسر', 'الى', 'الم', 'شدد', 'تطع', 'نوم', 'سبب', 'الم', 'فما', 'هوا', 'لحل', 'فضل']

 Question: الم في الفخد الايمن
 Processed Question: ['الم', 'فخد', 'ايم']

 Question: انا اعاني من انتفاضات مفاجاه في جسدي وتشنج بسيط في رقابتي نابعه من صدري وعندما تحدث اشعر بي الم في جسدي ويصعب علي التنفس والحديث لي بضع ثواني ونخز
 Processed Question: ['انا', 'اعا', 'نفض', 'فجا', 'جسد', 'شنج', 'بسط', 'رقب', 'نبع', 'صدر', 'عند', 'حدث', 'شعر', 'الم', 'جسد', 'صعب', 'علي', 'نفس', 'حدث', 'ثوا', 'نخز']

 Question: انا ام مرضعة عمر طفلتي تقريبا ثلاث اشهر والان وزني 65 واريد النزول الى وزن 57 كم سعرة حرارية احتاج يوميا وافضل طريقة لصرف سعرات اكثر يوميا
 Processed Question: ['انا', 'ام', 'رضع', 'عمر', 'طفل', 'قرب', 'شهر', 'وال', 'وزن', '65', 'ارد', 'نزل', 'الى', 'وزن', '57', 'سعر', 'حرر', 'حاج', 'يوم', 'فضل', 'طرق', 'صرف', 'سعر', 'كثر', 'يوم']

 Question: وزني ٥٩ طولي ١٥٠ ابي رجيم ينقص الوزن
 Processed Question: ['وزن', '٥٩', 'طول', '١٥٠', 'ابي', 'رجم', 'نقص', 'وزن']

 Question: شد من الخلف بالراس
 Processed Question: ['شد', 'خلف', 'راس']

 Question: اخوي مهلوس يسمع اصوات ووجود اشخاص حوالينه من كثر سماع الاصوات يبدا يشك ف الكل ويضرب من غير وعي كيف يتم علاجه وهل في ادويه هالحاله؟
 Processed Question: ['اخي', 'هلس', 'سمع', 'اصو', 'وجد', 'شخص', 'حلي', 'كثر', 'سمع', 'اصو', 'يبد', 'يشك', 'لكل', 'ضرب', 'وعي', 'يتم', 'علج', 'وهل', 'ادي', 'هالحال']

 Question: صباح الخير دكتور دكتوره انا تعبانه من اسناني ولثتي لدرجة انه اذني ويديني يعورني .. واحس الم ينبظ
 Processed Question: ['خير', 'دكتور', 'دكتور', 'انا', 'تعب', 'اسن', 'ولث', 'درج', 'انه', 'اذن', 'ويد', 'يعر', 'وحس', 'الم', 'نبظ']

 Question: بستشير دكتور
 Processed Question: ['تشر', 'دكتور']

 Question: السلام عليكم. دورتي متاخره والم بالفخوذ ونغزات وحرقه بالثدي ونفسيه جداً زفت مع افكار سلبيه وسواسس فترة ماقبل الدوره تكون متعبه من الافكار الوسواسيه بس
 Processed Question: ['سلم', 'علي', 'دور', 'تخر', 'ولم', 'فخذ', 'نغز', 'حرق', 'ثدي', 'نفس', 'جدا', 'زفت', 'فكر', 'سلب', 'سسس', 'فتر', 'اقبل', 'دور', 'تكون', 'تعب', 'فكر', 'سوس']

 Question: اعاني من الالم بالاسنان شديد بعد ماشربت عصير بارد اخذت حبوب روفيناك وزاد الالم اخذت المره الان اقدر اخذ شراب فيفادول وكم المقدار اللي اخذه حتى يسكن الالم ؟
 Processed Question: ['اعا', 'الم', 'اسن', 'شدد', 'اشرب', 'عصر', 'برد', 'اخذ', 'حبب', 'روف', 'وزد', 'الم', 'اخذ', 'مره', 'الن', 'قدر', 'اخذ', 'شرب', 'فدل', 'وكم', 'قدر', 'الل', 'اخذ', 'يسك', 'الم']

 Question: اعاني من الدهون والجلد المترهل
 Processed Question: ['اعا', 'دهن', 'جلد', 'ترهل']

 Question: زيادة الوززن
 Processed Question: ['زيد', 'وزز']

 Question: سمنه و وزني 80
 Processed Question: ['سمن', 'وزن', '80']

 Question: تاءكل في الغضاريف والم أثناء الحركة واسال عاي مدي فاعلية موف فري او كلوكوزامين
 Processed Question: ['تكل', 'غضاريف', 'ولم', 'حرك', 'اسل', 'عاي', 'مدي', 'فعل', 'موف', 'فري', 'او', 'كلوكوزام']

 Question: اعاني الام فوق عيني اليمنى
 Processed Question: ['اعا', 'الم', 'عين', 'منى']

 Question: دكتور عيون
 Processed Question: ['دكتور', 'عين']

 Question: وجود حبه في العين في الجفن العلوي من الداخل.
 Processed Question: ['وجد', 'حبه', 'عين', 'جفن', 'علي', 'دخل']

 Question: السلام عليكم انا عندي احد الاسنان الاماميه مكسوره ولما رحت للدكتور قال محتاج خلع ماهو افضل للسن البديل
 Processed Question: ['سلم', 'علي', 'انا', 'عند', 'احد', 'اسن', 'ممي', 'كسر', 'ولم', 'رحت', 'دكتور', 'قال', 'حتج', 'خلع', 'اهو', 'فضل', 'للس', 'بدل']

 Question: اعاني من الم الاسنان مستمر من ٣ ايام و ذهبت للدكتور و قالي ان في جيوب في اللثه هل جيوب اللثه تسبب هذا الالم
 Processed Question: ['اعا', 'الم', 'اسن', 'سمر', '٣', 'ايم', 'ذهب', 'دكتور', 'قلي', 'ان', 'جيب', 'لثه', 'جيب', 'لثه', 'سبب', 'الم']

 Question: عندي انتفاخ في جفن العبن اليمنى العلوي في مع حراره بسيطه في طرف العين من الداخل
 Processed Question: ['عند', 'نفخ', 'جفن', 'عبن', 'منى', 'علي', 'حرر', 'بسط', 'طرف', 'عين', 'دخل']

 Question: حضرتك انا كنت بعاني من حساسية في العين مع الشعور بوجود رمل في العين واحمرار
 Processed Question: ['حضر', 'انا', 'كنت', 'بعا', 'حسس', 'عين', 'شعر', 'وجد', 'رمل', 'عين', 'حمرار']

 Question: ضيق نفس مع خفقان قلب مع دوخه يذهب ويعود من شهر .. ما المشكلة
 Processed Question: ['ضيق', 'خفق', 'قلب', 'دوخ', 'ذهب', 'يعد', 'شهر', 'شكل']

 Question: ابني 9 س لدية نزيف باحدى عينه و انفصال شبكي كلي عملنا ليزر لتثبيت الشبكية و النزيف قل يستخدم قطرلت كورتيزون كل ساعتين و مضاد حيوي لكن الالتهاب لا يزول
 Processed Question: ['ابن', '9', 'لده', 'نزف', 'حدى', 'عين', 'فصل', 'شبك', 'كلي', 'عمل', 'يزر', 'تثب', 'شبك', 'نزف', 'قل', 'خدم', 'قطرل', 'كورتيز', 'ساع', 'ضاد', 'حيي', 'لهب', 'يزل']

 Question: neck pain for over 2 weeks now, and today I cannot move my neck
 Processed Question: ['neck', 'pain', 'for', 'over', '2', 'weeks', 'now', 'and', 'today', 'I', 'can', 'not', 'move', 'my', 'neck']

 Question: السلام عليكم
 Processed Question: ['سلم', 'علي']

 Question: تساقط الشعر
 Processed Question: ['سقط', 'شعر']

 Question:  Mild spondylodegenerative changes of the dorsal spine with reduced bright T2 signal of the dorsal discs and marginal osteophytosis رجل 33 عام ما التشخيص والعلاج؟
 Processed Question: ['Mild', 'spondylodegenerative', 'changes', 'of', 'the', 'dorsal', 'spine', 'with', 'reduced', 'bright', 'T2', 'signal', 'of', 'the', 'dorsal', 'discs', 'and', 'marginal', 'osteophytosis', 'رجل', '33', 'عام', 'شخص', 'علج']

 Question: السمنه المفرطه
 Processed Question: ['سمن', 'فرط']

 Question: الم في الضرس واعاني من خروج دم من نفس الضرس
 Processed Question: ['الم', 'ضرس', 'وعا', 'خرج', 'دم', 'ضرس']

***Pre-processing using porter stemmer***

In [ ]:
!camel_data -i light

The following packages will be installed: 'dialectid-model26', 'morphology-db-msa-s31', 'disambig-mle-calima-msa-r13', 'morphology-db-lev-01', 'disambig-mle-calima-egy-r13', 'morphology-db-egy-r13', 'morphology-db-glf-01', 'morphology-db-msa-r13'
Downloading package 'dialectid-model26': 100% 371M/371M [00:10<00:00, 34.4MB/s]
Extracting package 'dialectid-model26': 100% 371M/371M [00:00<00:00, 518MB/s]
Downloading package 'morphology-db-msa-s31': 100% 44.8M/44.8M [00:04<00:00, 10.8MB/s]
Extracting package 'morphology-db-msa-s31': 100% 44.8M/44.8M [00:00<00:00, 445MB/s]
Downloading package 'disambig-mle-calima-msa-r13': 100% 88.7M/88.7M [00:02<00:00, 31.5MB/s]
Extracting package 'disambig-mle-calima-msa-r13': 100% 88.7M/88.7M [00:00<00:00, 535MB/s]
Downloading package 'morphology-db-lev-01': 100% 10.6M/10.6M [00:00<00:00, 40.4MB/s]
Extracting package 'morphology-db-lev-01': 100% 10.6M/10.6M [00:00<00:00, 551MB/s]
Downloading package 'disambig-mle-calima-egy-r13': 100% 27.2M/27.2M [00:00<00:00, 48.5MB/s]
Extracting package 'disambig-mle-calima-egy-r13': 100% 27.2M/27.2M [00:00<00:00, 555MB/s]
Downloading package 'morphology-db-egy-r13': 100% 67.3M/67.3M [00:01<00:00, 42.2MB/s]
Extracting package 'morphology-db-egy-r13': 100% 67.3M/67.3M [00:00<00:00, 558MB/s]
Downloading package 'morphology-db-glf-01': 100% 7.98M/7.98M [00:00<00:00, 24.6MB/s]
Extracting package 'morphology-db-glf-01': 100% 7.98M/7.98M [00:00<00:00, 539MB/s]
Downloading package 'morphology-db-msa-r13': 100% 40.5M/40.5M [00:00<00:00, 51.7MB/s]
Extracting package 'morphology-db-msa-r13': 100% 40.5M/40.5M [00:00<00:00, 560MB/s]

In [ ]:
from camel_tools.disambig.mle import MLEDisambiguator
disambig = MLEDisambiguator.pretrained()
def preprocessing_patient_camel(patient_Question):
    # Removing punctuation
    patient_Question = re.sub(r'[^\w\s]', ' ', patient_Question)
    #only returning the lexemma of the word using camel tools morphological analysis(lemmatization)
    analysis_output = disambig.disambiguate(patient_Question.split())
    lexemma = [res.analyses[0].analysis.get('lex', res.word) for res in analysis_output if res.analyses]
    ar_stopwords = set(stopwords.words('arabic'))
    ready= []
    for word in lexemma:
      # setting a standard
      word = re.sub(r'[إأآ]', 'ا', word)
      word = re.sub(r'ؤ', 'و', word)
      word = re.sub(r'ئ', 'ي', word)
      word = re.sub(r'ء', '', word)
      word = re.sub(r'ة', 'ه', word)
      # removing harkat
      word = re.sub(r'[\u064B-\u0652]', '', word)
      if word not in ar_stopwords:
        ready.append(word)
    return ready

In [ ]:
preprocessed_Question_camel = [preprocessing_patient_camel(text) for text in df['question_body']]

In [ ]:
for question, processed_qu in list(zip(df['question_body'], preprocessed_Question_camel))[:100]:
    print(f" Question: {question}")
    print(f" Processed Question: {processed_qu}\n")

 Question: أريد التحدث مع طبيب
 Processed Question: ['اراد', 'تحدث', 'طبيب']

 Question: فيني سمنه
 Processed Question: ['سمنه']

 Question: اريد نظام رجيم مناسب
 Processed Question: ['اراد', 'نظام', 'رجيم', 'مناسب']

 Question: صداع غثيان
 Processed Question: ['صداع', 'غثيان']

 Question: الم شديد جداً في فالجنب الايسر من الظهر من ٥ ايام مايفك ولاثانيه مع عدم القدره ع المشي والحركه والنوم رغم المسكنات
 Processed Question: ['الم', 'شديد', 'جد', 'جنب', 'ايسر', 'ظهر', '٥', 'يوم', 'مايفك', 'ولاثانيه', 'عدم', 'قدره', 'مشي', 'حركه', 'نوم', 'رغم', 'مسكن']

 Question: كيف ازيد طولي ماهو الشي الدي نعمله من شأن يزيد الطول
 Processed Question: ['زاد', 'طول', 'ماهو', 'شي', 'الد', 'عمل', 'شان', 'زاد', 'طول']

 Question: اعاني من القرنية المخروطية ولقد عملت عملية تثبيت للقرنية منذ ٣ سنوات ونجحت هل يمكنني الان عمل عملية ليزك لتصحيح بصري وترك النظارات؟
 Processed Question: ['عانى', 'قرني', 'مخروطي', 'عمل', 'عمليه', 'تثبيت', 'قرني', '٣', 'سنه', 'نجح', 'امكن', 'ان', 'عمل', 'عمليه', 'زكى', 'تصحيح', 'بصري', 'نظاره']

 Question: نزول كتل دم اثناء الدورة الشهرية
 Processed Question: ['زال', 'كتله', 'دم', 'ثني', 'دوره', 'شهري']

 Question: بنتي عمره شهرين ونص وكالوا احتمال عنده خلع ولادي تبقه من تكبر تعرج حتى لو تعالج
 Processed Question: ['بنت', 'عمر', 'شهر', 'نص', 'كال', 'ٱحتمال', 'خلع', 'اد', 'بقي', 'كبر', 'تعرج', 'عالج']

 Question: الم اسفل الظهر
 Processed Question: ['الم', 'اسفل', 'ظهر']

 Question: احمرار بالعينين مع افرازات، وانتفاخ بالجفن، وألم عند ضغطها ، وصداع.
 Processed Question: ['ٱحمرار', 'افراز', 'ٱنتفاخ', 'جفن', 'الم', 'ضغط', 'صداع']

 Question: طفلي عمر السنتين كان حولين عيونه حبوب ومحمره والان داخل العين حمراء
 Processed Question: ['طفل', 'عمر', 'سنه', 'حولين', 'حب', 'محمر', 'ان', 'داخل', 'احمر']

 Question: تناول الفيتامينات مع بعضها
 Processed Question: ['تناول', 'فيتامين', 'عض']

 Question: وجود مشاكل في النظام ونزول في الوزن
 Processed Question: ['وجود', 'مشكله', 'نظام', 'زال', 'وزن']

 Question: نعم اريد طيب جراحه عظام
 Processed Question: ['اراد', 'طيب', 'جرح', 'عظم']

 Question: اعاني من دمامل صغيرة في الثدي ظهرت لي بعد زيادة في الوزن هل السمنه هي السبب؟
 Processed Question: ['عانى', 'دمل', 'صغير', 'ثدي', 'ظهر', 'زياده', 'وزن', 'سمنه', 'سبب']

 Question: السلام عليكم دكتور عندي بقع صفرا ف بياض العين خقي ماادري من ايش
 Processed Question: ['سلام', 'دكتور', 'بقعه', 'صفر', 'بياض', 'خقي', 'ماادري', 'ايش']

 Question: الم شديد بالاسنان نتيجه نحت ضرس وبمجرد ماينتهي مفعول البنادول يرجع الالم
 Processed Question: ['الم', 'شديد', 'سن', 'نتيجه', 'نحت', 'ضرس', 'مجرد', 'ماينتهي', 'مفعول', 'البنادول', 'الم']

 Question: الم بالكتف
 Processed Question: ['الم', 'كتف']

 Question: زيادة هرمون الاستروجين
 Processed Question: ['زياده', 'هورمون', 'استروجين']

 Question: السمنه اريد الحصول على افضل حبوب انقاص الوزن
 Processed Question: ['سمنه', 'اراد', 'حصول', 'افضل', 'حب', 'انقاص', 'وزن']

 Question: ممكن استخدم الدواء FAST LOSE مع العلم استخدم مكملات غذائيه مثل فيتامين د و ب و اوميقا ثري مع العلم وزني ١٢٥ وعمري ٢٧ هل له اثار جانبية وهل هو امن ؟
 Processed Question: ['ممكن', 'ٱستخدم', 'دوا', 'FAST', 'LOSE', 'ٱستخدم', 'مكملات', 'غذايي', 'فيتامين', 'اوميقا', 'ثري', 'وزن', '١٢٥', 'عمر', '٢٧', 'اثار', 'جانبي', 'امن']

 Question: التهاب العين
 Processed Question: ['ٱلتهاب']

 Question: بنتي عمرها ٨ سنوات صارت مره نفسيه مو عارفه اتعامل معاها
 Processed Question: ['بنت', 'عمر', '٨', 'سنه', 'مره', 'نفسي', 'مو', 'عارف', 'تعامل', 'معى']

 Question: مفصل القدم
 Processed Question: ['مفصل', 'قدم']

 Question: عاوز اترك العاده ١٧ سنه
 Processed Question: ['عاوز', 'عاده', '١٧', 'سنه']

 Question: الم في الركبه
 Processed Question: ['الم', 'ركبه']

 Question: انا عندي تكيسات ووزني زايد وزني 90
 Processed Question: ['انا', 'تكيسات', 'وزن', 'زايد', 'وزن', '90']

 Question: لدي الم ركبة عند ثني الركبة على أثر وقعة يمتد أحياناً أسفل أو فوق الركبة الالم غير ثابت انا في بلد الطبابة فيه مكلفة وليس لدي تأمين أرجو المساعدة
 Processed Question: ['الم', 'ركبه', 'ثنى', 'ركبه', 'اثر', 'وقع', 'ٱمتد', 'اسفل', 'او', 'ركبه', 'الم', 'ثابت', 'انا', 'بلد', 'طبابه', 'مكلف', 'اليس', 'تامين', 'رجا', 'مساعده']

 Question: الالم في الجزء الأيسر العلوي من الثدي الايمن عند حركه الجسم للامام أو تحريك الكتف وعدم وجود أي تغير في شكل الثدي أو أي إفرازات أو أي عقد في أي منطقه سني ٢٠ سنه
 Processed Question: ['الم', 'جز', 'ايسر', 'علوي', 'ثدي', 'ايمن', 'حركه', 'جسم', 'امام', 'او', 'تحريك', 'كتف', 'عدم', 'وجود', 'اي', 'شكل', 'ثدي', 'او', 'اي', 'افراز', 'او', 'اي', 'عقد', 'اي', 'منطقه', 'سني', '٢٠', 'سنه']

 Question: اريد ان استشير كيف انزل وزني وخاصه البطن
 Processed Question: ['اراد', 'ان', 'ٱستشار', 'انزل', 'وزن', 'خاص', 'بطن']

 Question: مرحبا دكتور زوجي اقفل باب السياره على اصبعه من اسبوعين وراح المستشفى وتاكد انه مافي كسر ولكن مايزال الاصبع متورم وفيه دم اسود ايش الحل
 Processed Question: ['مرحبا', 'دكتور', 'زوج', 'اقفل', 'باب', 'سياره', 'اصبع', 'اسبوع', 'مستشفى', 'تاكد', 'ان', 'مافي', 'كسر', 'لٰكن', 'زال', 'اصبع', 'متورم', 'دم', 'اسود', 'ايش', 'حل']

 Question: بياض لسان يشبه الفرو
 Processed Question: ['بياض', 'لسان', 'اشبه', 'فرو']

 Question: حبه في جفن عيني من الداخل
 Processed Question: ['حب', 'جفن', 'داخل']

 Question: طبيبه نساء اعاني من اعراض البرد من دوخه واستفراغ وغثيان
 Processed Question: ['طبيب', 'نسا', 'عانى', 'عرض', 'برد', 'دوخ', 'ٱستفراغ', 'غثيان']

 Question: السلام عليكم ورحمة الله لدي مشكلة نفسية (الرهاب الاجتماعي) منذ أكثر من ١٠ سنوات، بسبب موقف محرج حدث لي، أحتاج من يساعدني
 Processed Question: ['سلام', 'رحمه', 'الله', 'مشكله', 'نفسي', 'الرهاب', 'ٱجتماعي', 'اكثر', '١٠', 'سنه', 'سبب', 'موقف', 'محرج', 'حدث', 'ٱحتاج', 'ساعد']

 Question: ١-ازيثرومايسين مضاد عن العدوى البكتيريه ولعلاج اثار كورونا ! ٢-تيليفاست مضاد الهستامين ٣-توبريكس عن التهاب الملتحمه والقرنيه دكتور تشرحلي ليش رقم ١ !؟
 Processed Question: ['١', 'ازيثرومايسين', 'مضاد', 'عدوى', 'بكتيري', 'علاج', 'اثار', 'كور', '٢', 'تيليفاست', 'مضاد', 'الهستامين', '٣', 'توبريكس', 'ٱلتهاب', 'ملتحم', 'قرني', 'دكتور', 'تشرحلي', 'ليش', 'رقم', '١']

 Question: انا حصلت عندي ضربة في المرفق وانا اخذ شاور وكانت ضربة قوية ضربت في عمود حديدي " لتعليق المناشف " من بعد ذلك والمرفق انزاح من مكانه ويصدر اصوات طقطقه.
 Processed Question: ['انا', 'حصل', 'ضربه', 'مرفق', 'انا', 'اخذ', 'شاور', 'ضربه', 'قوي', 'ضرب', 'عمود', 'حديدي', 'تعليق', 'منشفه', 'ذٰلك', 'مرفق', 'نزح', 'مكان', 'اصدر', 'صوت', 'طقطقه']

 Question: مشكلة لدى والدي عمره ٥٩ سنة - يوجد عنده خشونه في الركبة و التهاب يعاني الان من الاآم في الركبة و يوجد تخشب في الاطراف مع العلم يعاني من مرض السكر
 Processed Question: ['مشكله', 'والد', 'عمر', '٥٩', 'سنه', 'خشونه', 'ركبه', 'ٱلتهاب', 'عانى', 'ان', 'الاام', 'ركبه', 'تخشب', 'طرف', 'عانى', 'مرض', 'سكر']

 Question: السلام عليكم ابنتي حفرة قدمها مائل قليلا الطبيب شك انه خلع ولاده وصورت اليوم تصوير تلفزيوني
 Processed Question: ['سلام', 'ٱبنه', 'حفره', 'قدم', 'مايل', 'قليل', 'طبيب', 'شك', 'ان', 'خلع', 'ولاده', 'صور', 'يوم', 'تصوير', 'تلفزيوني']

 Question: السلام عليكم دكتور هذا حال اظافر رجلي بالذات الظفر الكبير قبل طلعلي ظفر غائر وعانيت وعالجت بعدها عرفت كيف اقص اظافري من بعدها صارت اظافري كذا لست اعلم
 Processed Question: ['سلام', 'دكتور', 'هٰذا', 'حال', 'ظفر', 'رجل', 'ظفر', 'كبير', 'طلعلي', 'ظفر', 'غاير', 'عانى', 'عالج', 'عرف', 'قص', 'ظفر', 'ظفر', 'لاس']

 Question: ابني عنيف في بعض الاحيان ومشاغب و بيعمل سلوكيات خاطئه
 Processed Question: ['ٱبن', 'عنيف', 'عض', 'مشاغب', 'بيعمل', 'سلوكي', 'خاطي']

 Question: ظهري يؤلمني من لوح الكتف وبينزل الوجع لتحت
 Processed Question: ['ظهر', 'الم', 'لوح', 'كتف', 'وبينزل', 'وجع', 'حت']

 Question: مشكله بروز الفك العلوي
 Processed Question: ['مشكله', 'بروز', 'الف', 'علوي']

 Question: السلام عليكم انا عندي تقوس في الرجل وش الحل ؟
 Processed Question: ['سلام', 'انا', 'تقوس', 'رجل', 'وش', 'حل']

 Question: ابني عمره ٨ سنوات عنده شعور الرغبه بأكل شعر الرأس لاكنه لايفعل وسبب له توتر
 Processed Question: ['ٱبن', 'عمر', '٨', 'سنه', 'شعور', 'رغبه', 'اكل', 'شعر', 'راس', 'لايفعل', 'سبب', 'توتر']

 Question: عن العظام
 Processed Question: ['عظم']

 Question: تمنيل اطرافي
 Processed Question: ['تمنيل', 'طرف']

 Question: في حاجه دخلت عيني او جرحتها بالغلط وهي مره قاعده تعورني مو قادره افتحها
 Processed Question: ['حاجه', 'دخل', 'او', 'جرح', 'غلط', 'مره', 'قاعده', 'عور', 'مو', 'قادر', 'فتح']

 Question: بعاني من النحافه وأخذت ترياكتين لمده ٣ ايام وبعدين بطلت ورجعت بعد شهرين اخدت عشرين يوم مواصلين وبعدين بطلت تاني اخدت شوكلاته لزياده الحديد ومفيش فايد
 Processed Question: ['عاني', 'نحافه', 'اخذ', 'ترياكتين', 'مده', '٣', 'يوم', 'بطل', 'شهر', 'اخدت', 'يوم', 'مواصلين', 'بطل', 'تاني', 'اخدت', 'شوكلاته', 'زياده', 'حديد', 'ومفيش', 'يد']

 Question: عندي رتباك عند فعل اي شيء امام الآخرين ...مع تحرك الاطراف
 Processed Question: ['رتب', 'فعل', 'اي', 'شي', 'امام', 'اخر', 'تحرك', 'طرف']

 Question: نزعت عصب ونظفت خراج وحطيت حشوه مؤقته وتسبب لي الخراج بتورم شديد وتنمل بالوجه واليوم طلع لي هذا باللثه وش السبب؟؟؟
 Processed Question: ['نزع', 'عصب', 'نظف', 'خراج', 'وحطيت', 'حشو', 'موقت', 'تسبب', 'خراج', 'تورم', 'شديد', 'نمل', 'وجه', 'يوم', 'طلع', 'هٰذا', 'لثه', 'وش', 'سبب']

 Question: استشاري عظام
 Processed Question: ['ٱستشاري', 'عظم']

 Question: الام الضرس
 Processed Question: ['ام', 'ضرس']

 Question: Tawuniya اشعر بالم شديد في الفك هل يوجد حل مؤقت لتسكين الالم مثل الكمادات مثلا او شي اخر؟
 Processed Question: ['Tawuniya', 'شعر', 'بالم', 'شديد', 'الف', 'حل', 'موقت', 'تسكين', 'الم', 'الكمادات', 'او', 'شي', 'اخر']

 Question: كنت بتكلم عادى مع الصيدليى يوم الخميس دخت ووقعت ومناخيرى وبقى اتفتحوا قسلى الضغط واطى جدا بعد كده الجمعة ورم فى بقى السبت فى مناخيرى الاحد فى عينى
 Processed Question: ['تكلم', 'عادي', 'الصيدليي', 'يوم', 'داخ', 'وقع', 'منخار', 'بقي', 'اتفتحوا', 'قسلي', 'ضغط', 'واطي', 'جد', 'كد', 'جمعه', 'ورم', 'بقي', 'منخار', 'احد']

 Question: أعاني من مرض في الشبكية وأنا الآم لي أسبوعين تقريبًا صرت أشوف زي النور الابيض المتقطع في جانب عيني ولا أدري ايش هذا النور وايش سببه
 Processed Question: ['عانى', 'مرض', 'شبكي', 'انا', 'ام', 'اسبوع', 'تقريب', 'شاف', 'زي', 'نور', 'ابيض', 'متقطع', 'جانب', 'ايش', 'هٰذا', 'نور', 'وايش', 'سبب']

 Question: زوجتي ٣٠ عاما تعاني من الم ف الكتف الايسر وتحت الكتف قليلا من الامام والخلف واحيانا تشعر بسخونة ف نفس المكان ولكن الالم غير مستمر
 Processed Question: ['زوجه', '٣٠', 'عام', 'عانى', 'الم', 'كتف', 'ايسر', 'كتف', 'قليل', 'امام', 'شعر', 'سخونه', 'مكان', 'لٰكن', 'الم', 'مستمر']

 Question: عندي الم في رجلي اليمنى من اعلى الفخذ لاخر الساق وقت النوم ويزيد مع البرد لدرجة يمنعني من النوم مستمر الالم من سنين وما احس فيه باقي اليوم
 Processed Question: ['الم', 'رجل', 'يمنى', 'اعلى', 'فخذ', 'اخر', 'ساق', 'وقت', 'نوم', 'زاد', 'برد', 'درجه', 'منع', 'نوم', 'مستمر', 'الم', 'سنه', 'حسس', 'باقي', 'يوم']

 Question: مرحبا قدمي تورمت قليلا لانها انصدمت بكرسي حديد
 Processed Question: ['مرحبا', 'قدم', 'تورم', 'قليل', 'ان', 'انصدمت', 'كرسي', 'حديد']

 Question: اعاني من زياده الوزن
 Processed Question: ['عانى', 'زياده', 'وزن']

 Question: بضغض على اسنانى منذ حوالي اربع ايام
 Processed Question: ['بضغض', 'سن', 'حوال', 'اربع', 'يوم']

 Question: الم في الكعب الرجل
 Processed Question: ['الم', 'كعب', 'رجل']

 Question: عملت سحب عصب للاسنان قبل اسبوع لابني والى الان يعاني من الن قوي حتى بغد اخذ المسكن
 Processed Question: ['عمل', 'سحب', 'عصب', 'سن', 'اسبوع', 'ٱبن', 'الى', 'ان', 'عانى', 'الان', 'قوي', 'غد', 'اخذ', 'مسكن']

 Question: ارجوشاكرامساعدتي في تحديد المرض الذي اعاني منه في مفصل الركبه اليسرى خلال الأسبوعين الماضيين  اضافة الى ظهور تورم حول مفصل الركبه ويمتد الى اسفل القدم
 Processed Question: ['ارجوشاكرامساعدتي', 'تحديد', 'مرض', 'عانى', 'مفصل', 'ركبه', 'ايسر', 'خلال', 'اسبوع', 'ماضي', 'اضافه', 'الى', 'ظهور', 'تورم', 'حول', 'مفصل', 'ركبه', 'ٱمتد', 'الى', 'اسفل', 'قدم']

 Question: خدش بالقرنيه
 Processed Question: ['خدش', 'قرني']

 Question: ابه أستشير دكتور مكالمه استشاره عن علاج
 Processed Question: ['اب', 'ٱستشار', 'دكتور', 'مكالمه', 'ٱستشاره', 'علاج']

 Question: زوجي كان مستمر على ادوية الاكتئاب 3 سنين وتركها فجاءه بعدها بشهرين سائت حالته يشعر بدوخه وكهربا بالراس والم بالعظام واكتئاب وحاول الرجوع شهر وماكان لهامفعول وتركها الان ماهو الحل هل الرجوع لها هو الحل
 Processed Question: ['زوج', 'مستمر', 'دوا', 'ٱكتياب', '3', 'سنه', 'جا', 'شهر', 'سايت', 'حاله', 'شعر', 'دوخه', 'كهرب', 'راس', 'الم', 'عظيم', 'ٱكتياب', 'حاول', 'رجوع', 'شهر', 'وماكان', 'لهامفعول', 'ان', 'ماهو', 'حل', 'رجوع', 'حل']

 Question: هل هنالك مخاطر عند استعمال المكمل الغذائي ‏Centrum-سينتروم
 Processed Question: ['مخاطر', 'ٱستعمال', 'مكمل', 'غذايي', 'Centrum', 'سينتروم']

 Question: مرحبا بنتي عمرها ١٠ شهور ونص ولسى م تحبي بس تزحف واذا وقفتها رجلها اليسرى ترفعها هذي صور الاشعه
 Processed Question: ['مرحبا', 'بنت', 'عمر', '١٠', 'شهر', 'نص', 'سي', 'احب', 'زحف', 'اذا', 'وقف', 'رجل', 'ايسر', 'رفع', 'هٰذا', 'صور', 'شعاع']

 Question: زوجتي حامل في الشهر الخامس وبسبب حملها لغرض ما بيدها وبطريقة خاطئة تعرض ذراعها الايسر الى الم شديد لا تستطيع النوم بسبب الالم فما هوا الحل من فضلكم
 Processed Question: ['زوجه', 'حامل', 'شهر', 'سبب', 'حمل', 'غرض', 'يد', 'طريقه', 'خاطي', 'تعرض', 'ذراع', 'ايسر', 'الى', 'الم', 'شديد', 'ٱستطاع', 'نوم', 'سبب', 'الم', 'هوا', 'حل', 'فضل']

 Question: الم في الفخد الايمن
 Processed Question: ['الم', 'الفخد', 'ايمن']

 Question: انا اعاني من انتفاضات مفاجاه في جسدي وتشنج بسيط في رقابتي نابعه من صدري وعندما تحدث اشعر بي الم في جسدي ويصعب علي التنفس والحديث لي بضع ثواني ونخز
 Processed Question: ['انا', 'عانى', 'ٱنتفاضه', 'مفاجاه', 'جسد', 'تشنج', 'بسيط', 'رقابه', 'نابع', 'صدري', 'تحدث', 'شعر', 'الم', 'جسد', 'صعب', 'تنفس', 'حديث', 'ثانيه', 'نخز']

 Question: انا ام مرضعة عمر طفلتي تقريبا ثلاث اشهر والان وزني 65 واريد النزول الى وزن 57 كم سعرة حرارية احتاج يوميا وافضل طريقة لصرف سعرات اكثر يوميا
 Processed Question: ['انا', 'ام', 'مرضع', 'عمر', 'طفل', 'تقريب', 'شهر', 'ان', 'وزن', '65', 'اراد', 'نزول', 'الى', 'وزن', '57', 'سعر', 'حراري', 'ٱحتاج', 'يومي', 'افضل', 'طريقه', 'صرف', 'سعرات', 'اكثر', 'يومي']

 Question: وزني ٥٩ طولي ١٥٠ ابي رجيم ينقص الوزن
 Processed Question: ['وزن', '٥٩', 'طول', '١٥٠', 'ابي', 'رجيم', 'نقص', 'وزن']

 Question: شد من الخلف بالراس
 Processed Question: ['شد', 'راس']

 Question: اخوي مهلوس يسمع اصوات ووجود اشخاص حوالينه من كثر سماع الاصوات يبدا يشك ف الكل ويضرب من غير وعي كيف يتم علاجه وهل في ادويه هالحاله؟
 Processed Question: ['اخ', 'مهلوس', 'سمع', 'صوت', 'وجود', 'شخص', 'حوالينه', 'كثر', 'سماع', 'صوت', 'بدا', 'شك', 'ضرب', 'وعي', 'تم', 'علاج', 'دوا', 'هالحاله']

 Question: صباح الخير دكتور دكتوره انا تعبانه من اسناني ولثتي لدرجة انه اذني ويديني يعورني .. واحس الم ينبظ
 Processed Question: ['خير', 'دكتور', 'دكتور', 'انا', 'عب', 'سن', 'لثه', 'درجه', 'ان', 'اذن', 'ودى', 'عور', 'حسس', 'الم', 'ينبظ']

 Question: بستشير دكتور
 Processed Question: ['بستشير', 'دكتور']

 Question: السلام عليكم. دورتي متاخره والم بالفخوذ ونغزات وحرقه بالثدي ونفسيه جداً زفت مع افكار سلبيه وسواسس فترة ماقبل الدوره تكون متعبه من الافكار الوسواسيه بس
 Processed Question: ['سلام', 'دوره', 'متاخر', 'الم', 'بالفخوذ', 'ونغزات', 'حرق', 'ثدي', 'نفسي', 'جد', 'زفت', 'فكر', 'سلبي', 'وسواسس', 'فتره', 'ماقبل', 'دوره', 'متعب', 'فكر', 'الوسواسيه']

 Question: اعاني من الالم بالاسنان شديد بعد ماشربت عصير بارد اخذت حبوب روفيناك وزاد الالم اخذت المره الان اقدر اخذ شراب فيفادول وكم المقدار اللي اخذه حتى يسكن الالم ؟
 Processed Question: ['عانى', 'الم', 'سن', 'شديد', 'ماشربت', 'عصير', 'بارد', 'اخذ', 'حب', 'روفيناك', 'زاد', 'الم', 'اخذ', 'مره', 'ان', 'قدر', 'اخذ', 'شراب', 'فيفادول', 'مقدار', 'اخذ', 'سكن', 'الم']

 Question: اعاني من الدهون والجلد المترهل
 Processed Question: ['عانى', 'دهن', 'جلد', 'مترهل']

 Question: زيادة الوززن
 Processed Question: ['زياده', 'الوززن']

 Question: سمنه و وزني 80
 Processed Question: ['سمنه', 'وزن', '80']

 Question: تاءكل في الغضاريف والم أثناء الحركة واسال عاي مدي فاعلية موف فري او كلوكوزامين
 Processed Question: ['تاكل', 'غضروف', 'الم', 'ثني', 'حركه', 'اسال', 'عاي', 'مدى', 'فاعليه', 'موفي', 'ري', 'او', 'كلوكوزامين']

 Question: اعاني الام فوق عيني اليمنى
 Processed Question: ['عانى', 'ام', 'يمنى']

 Question: دكتور عيون
 Processed Question: ['دكتور']

 Question: وجود حبه في العين في الجفن العلوي من الداخل.
 Processed Question: ['وجود', 'حب', 'جفن', 'علوي', 'داخل']

 Question: السلام عليكم انا عندي احد الاسنان الاماميه مكسوره ولما رحت للدكتور قال محتاج خلع ماهو افضل للسن البديل
 Processed Question: ['سلام', 'انا', 'احد', 'سن', 'امامي', 'مكسور', 'دكتور', 'قال', 'محتاج', 'خلع', 'ماهو', 'افضل', 'سن', 'بديل']

 Question: اعاني من الم الاسنان مستمر من ٣ ايام و ذهبت للدكتور و قالي ان في جيوب في اللثه هل جيوب اللثه تسبب هذا الالم
 Processed Question: ['عانى', 'الم', 'سن', 'مستمر', '٣', 'يوم', 'دكتور', 'قالي', 'ان', 'جيب', 'لثه', 'جيب', 'لثه', 'تسبب', 'هٰذا', 'الم']

 Question: عندي انتفاخ في جفن العبن اليمنى العلوي في مع حراره بسيطه في طرف العين من الداخل
 Processed Question: ['ٱنتفاخ', 'جفن', 'العبن', 'يمنى', 'علوي', 'حراره', 'بسيط', 'طرف', 'داخل']

 Question: حضرتك انا كنت بعاني من حساسية في العين مع الشعور بوجود رمل في العين واحمرار
 Processed Question: ['حضره', 'انا', 'عاني', 'حساسي', 'شعور', 'وجود', 'رمل', 'ٱحمرار']

 Question: ضيق نفس مع خفقان قلب مع دوخه يذهب ويعود من شهر .. ما المشكلة
 Processed Question: ['ضيق', 'خفقان', 'قلب', 'دوخ', 'شهر', 'مشكله']

 Question: ابني 9 س لدية نزيف باحدى عينه و انفصال شبكي كلي عملنا ليزر لتثبيت الشبكية و النزيف قل يستخدم قطرلت كورتيزون كل ساعتين و مضاد حيوي لكن الالتهاب لا يزول
 Processed Question: ['ٱبن', '9', 'نزيف', 'احد', 'ٱنفصال', 'شبكي', 'كلي', 'عمل', 'زار', 'تثبيت', 'شبكي', 'نزيف', 'قال', 'ٱستخدم', 'قطرلت', 'كورتيزون', 'ساعه', 'مضاد', 'حيوي', 'لٰكن', 'ٱلتهاب', 'زال']

 Question: neck pain for over 2 weeks now, and today I cannot move my neck
 Processed Question: ['neck', 'pain', 'for', 'over', '2', 'weeks', 'now', 'and', 'today', 'I', 'cannot', 'move', 'my', 'neck']

 Question: السلام عليكم
 Processed Question: ['سلام']

 Question: تساقط الشعر
 Processed Question: ['تساقط', 'شعر']

 Question:  Mild spondylodegenerative changes of the dorsal spine with reduced bright T2 signal of the dorsal discs and marginal osteophytosis رجل 33 عام ما التشخيص والعلاج؟
 Processed Question: ['Mild', 'spondylodegenerative', 'changes', 'of', 'the', 'dorsal', 'spine', 'with', 'reduced', 'bright', 'T2', 'signal', 'of', 'the', 'dorsal', 'discs', 'and', 'marginal', 'osteophytosis', 'رجل', '33', 'عام', 'تشخيص', 'علاج']

 Question: السمنه المفرطه
 Processed Question: ['سمنه', 'مفرط']

 Question: الم في الضرس واعاني من خروج دم من نفس الضرس
 Processed Question: ['الم', 'ضرس', 'عانى', 'خروج', 'دم', 'ضرس']

***Pre-processing using Simple Lemmetation (RE)***

In [ ]:
def preprocessing_patient_RE_lemmatization (patient_Question):
    # setting a standard
    patient_Question = re.sub(r'[إأآ]', 'ا', patient_Question)
    patient_Question = re.sub(r'ؤ', 'و', patient_Question)
    patient_Question = re.sub(r'ئ', 'ي', patient_Question)
    patient_Question = re.sub(r'ء', '', patient_Question)
    patient_Question = re.sub(r'ة', 'ه', patient_Question)
    # removing harkat
    patient_Question = re.sub(r'[\u064B-\u0652]', '', patient_Question)
    # Removing punctuation
    patient_Question = re.sub(r'[^\w\s]', ' ', patient_Question)
    # tokenization
    tokens = nltk.word_tokenize(patient_Question)
    # Remove stopwords
    ar_stopwords = set(stopwords.words('arabic'))
    without_stop = [word for word in tokens if word not in ar_stopwords]
    #lemmatization using regular ewxpressions where we manualy remove the parts of the word that are not from the lexemma
    lemmatized_re = [re.sub(r'(هات|ات|ون|ين|ان|يه|ها|هم|كم|نا|ه|ي|ة|ا)$', '', word) for word in without_stop]
    return lemmatized_re

In [ ]:
preprocessed_Question_RE_lemmatized = [preprocessing_patient_RE_lemmatization(text) for text in df['question_body']]

In [ ]:
for question, processed_qu in list(zip(df['question_body'], preprocessed_Question_RE_lemmatized))[:100]:
  print(f" Question: {question}")
  print(f" Processed Question: {processed_qu}\n")

 Question: أريد التحدث مع طبيب
 Processed Question: ['اريد', 'التحدث', 'طبيب']

 Question: فيني سمنه
 Processed Question: ['فين', 'سمن']

 Question: اريد نظام رجيم مناسب
 Processed Question: ['اريد', 'نظام', 'رجيم', 'مناسب']

 Question: صداع غثيان
 Processed Question: ['صداع', 'غثي']

 Question: الم شديد جداً في فالجنب الايسر من الظهر من ٥ ايام مايفك ولاثانيه مع عدم القدره ع المشي والحركه والنوم رغم المسكنات
 Processed Question: ['الم', 'شديد', 'جد', 'فالجنب', 'الايسر', 'الظهر', '٥', 'ايام', 'مايفك', 'ولاثان', 'عدم', 'القدر', 'المش', 'والحرك', 'والنوم', 'رغم', 'المسكن']

 Question: كيف ازيد طولي ماهو الشي الدي نعمله من شأن يزيد الطول
 Processed Question: ['ازيد', 'طول', 'ماهو', 'الش', 'الد', 'نعمل', 'ش', 'يزيد', 'الطول']

 Question: اعاني من القرنية المخروطية ولقد عملت عملية تثبيت للقرنية منذ ٣ سنوات ونجحت هل يمكنني الان عمل عملية ليزك لتصحيح بصري وترك النظارات؟
 Processed Question: ['اعان', 'القرن', 'المخروط', 'ولقد', 'عملت', 'عمل', 'تثبيت', 'للقرن', '٣', 'سنو', 'ونجحت', 'يمكنن', 'ال', 'عمل', 'عمل', 'ليزك', 'لتصحيح', 'بصر', 'وترك', 'النظار']

 Question: نزول كتل دم اثناء الدورة الشهرية
 Processed Question: ['نزول', 'كتل', 'دم', 'الدور', 'الشهر']

 Question: بنتي عمره شهرين ونص وكالوا احتمال عنده خلع ولادي تبقه من تكبر تعرج حتى لو تعالج
 Processed Question: ['بنت', 'عمر', 'شهر', 'ونص', 'وكالو', 'احتمال', 'عند', 'خلع', 'ولاد', 'تبق', 'تكبر', 'تعرج', 'تعالج']

 Question: الم اسفل الظهر
 Processed Question: ['الم', 'اسفل', 'الظهر']

 Question: احمرار بالعينين مع افرازات، وانتفاخ بالجفن، وألم عند ضغطها ، وصداع.
 Processed Question: ['احمرار', 'بالعين', 'افراز', 'وانتفاخ', 'بالجفن', 'والم', 'ضغط', 'وصداع']

 Question: طفلي عمر السنتين كان حولين عيونه حبوب ومحمره والان داخل العين حمراء
 Processed Question: ['طفل', 'عمر', 'السنت', 'حول', 'عيون', 'حبوب', 'ومحمر', 'وال', 'داخل', 'الع', 'حمر']

 Question: تناول الفيتامينات مع بعضها
 Processed Question: ['تناول', 'الفيتامين', 'بعض']

 Question: وجود مشاكل في النظام ونزول في الوزن
 Processed Question: ['وجود', 'مشاكل', 'النظام', 'ونزول', 'الوزن']

 Question: نعم اريد طيب جراحه عظام
 Processed Question: ['اريد', 'طيب', 'جراح', 'عظام']

 Question: اعاني من دمامل صغيرة في الثدي ظهرت لي بعد زيادة في الوزن هل السمنه هي السبب؟
 Processed Question: ['اعان', 'دمامل', 'صغير', 'الثد', 'ظهرت', 'زياد', 'الوزن', 'السمن', 'السبب']

 Question: السلام عليكم دكتور عندي بقع صفرا ف بياض العين خقي ماادري من ايش
 Processed Question: ['السلام', 'علي', 'دكتور', 'عند', 'بقع', 'صفر', 'بياض', 'الع', 'خق', 'ماادر', 'ايش']

 Question: الم شديد بالاسنان نتيجه نحت ضرس وبمجرد ماينتهي مفعول البنادول يرجع الالم
 Processed Question: ['الم', 'شديد', 'بالاسن', 'نتيج', 'نحت', 'ضرس', 'وبمجرد', 'ماينته', 'مفعول', 'البنادول', 'يرجع', 'الالم']

 Question: الم بالكتف
 Processed Question: ['الم', 'بالكتف']

 Question: زيادة هرمون الاستروجين
 Processed Question: ['زياد', 'هرم', 'الاستروج']

 Question: السمنه اريد الحصول على افضل حبوب انقاص الوزن
 Processed Question: ['السمن', 'اريد', 'الحصول', 'افضل', 'حبوب', 'انقاص', 'الوزن']

 Question: ممكن استخدم الدواء FAST LOSE مع العلم استخدم مكملات غذائيه مثل فيتامين د و ب و اوميقا ثري مع العلم وزني ١٢٥ وعمري ٢٧ هل له اثار جانبية وهل هو امن ؟
 Processed Question: ['ممكن', 'استخدم', 'الدو', 'FAST', 'LOSE', 'العلم', 'استخدم', 'مكمل', 'غذاي', 'فيتام', 'اوميق', 'ثر', 'العلم', 'وزن', '١٢٥', 'وعمر', '٢٧', 'اثار', 'جانب', 'وهل', 'امن']

 Question: التهاب العين
 Processed Question: ['التهاب', 'الع']

 Question: بنتي عمرها ٨ سنوات صارت مره نفسيه مو عارفه اتعامل معاها
 Processed Question: ['بنت', 'عمر', '٨', 'سنو', 'صارت', 'مر', 'نفس', 'مو', 'عارف', 'اتعامل', 'معا']

 Question: مفصل القدم
 Processed Question: ['مفصل', 'القدم']

 Question: عاوز اترك العاده ١٧ سنه
 Processed Question: ['عاوز', 'اترك', 'العاد', '١٧', 'سن']

 Question: الم في الركبه
 Processed Question: ['الم', 'الركب']

 Question: انا عندي تكيسات ووزني زايد وزني 90
 Processed Question: ['ا', 'عند', 'تكيس', 'ووزن', 'زايد', 'وزن', '90']

 Question: لدي الم ركبة عند ثني الركبة على أثر وقعة يمتد أحياناً أسفل أو فوق الركبة الالم غير ثابت انا في بلد الطبابة فيه مكلفة وليس لدي تأمين أرجو المساعدة
 Processed Question: ['لد', 'الم', 'ركب', 'ثن', 'الركب', 'اثر', 'وقع', 'يمتد', 'احيا', 'اسفل', 'او', 'الركب', 'الالم', 'ثابت', 'ا', 'بلد', 'الطباب', 'مكلف', 'وليس', 'لد', 'تام', 'ارجو', 'المساعد']

 Question: الالم في الجزء الأيسر العلوي من الثدي الايمن عند حركه الجسم للامام أو تحريك الكتف وعدم وجود أي تغير في شكل الثدي أو أي إفرازات أو أي عقد في أي منطقه سني ٢٠ سنه
 Processed Question: ['الالم', 'الجز', 'الايسر', 'العلو', 'الثد', 'الايمن', 'حرك', 'الجسم', 'للامام', 'او', 'تحريك', 'الكتف', 'وعدم', 'وجود', 'ا', 'تغير', 'شكل', 'الثد', 'او', 'ا', 'افراز', 'او', 'ا', 'عقد', 'ا', 'منطق', 'سن', '٢٠', 'سن']

 Question: اريد ان استشير كيف انزل وزني وخاصه البطن
 Processed Question: ['اريد', '', 'استشير', 'انزل', 'وزن', 'وخاص', 'البطن']

 Question: مرحبا دكتور زوجي اقفل باب السياره على اصبعه من اسبوعين وراح المستشفى وتاكد انه مافي كسر ولكن مايزال الاصبع متورم وفيه دم اسود ايش الحل
 Processed Question: ['مرحب', 'دكتور', 'زوج', 'اقفل', 'باب', 'السيار', 'اصبع', 'اسبوع', 'وراح', 'المستشفى', 'وتاكد', 'ان', 'ماف', 'كسر', 'مايزال', 'الاصبع', 'متورم', 'وف', 'دم', 'اسود', 'ايش', 'الحل']

 Question: بياض لسان يشبه الفرو
 Processed Question: ['بياض', 'لس', 'يشب', 'الفرو']

 Question: حبه في جفن عيني من الداخل
 Processed Question: ['حب', 'جفن', 'عين', 'الداخل']

 Question: طبيبه نساء اعاني من اعراض البرد من دوخه واستفراغ وغثيان
 Processed Question: ['طبيب', 'نس', 'اعان', 'اعراض', 'البرد', 'دوخ', 'واستفراغ', 'وغثي']

 Question: السلام عليكم ورحمة الله لدي مشكلة نفسية (الرهاب الاجتماعي) منذ أكثر من ١٠ سنوات، بسبب موقف محرج حدث لي، أحتاج من يساعدني
 Processed Question: ['السلام', 'علي', 'ورحم', 'الل', 'لد', 'مشكل', 'نفس', 'الرهاب', 'الاجتماع', 'اكثر', '١٠', 'سنو', 'بسبب', 'موقف', 'محرج', 'حدث', 'احتاج', 'يساعدن']

 Question: ١-ازيثرومايسين مضاد عن العدوى البكتيريه ولعلاج اثار كورونا ! ٢-تيليفاست مضاد الهستامين ٣-توبريكس عن التهاب الملتحمه والقرنيه دكتور تشرحلي ليش رقم ١ !؟
 Processed Question: ['١', 'ازيثرومايس', 'مضاد', 'العدوى', 'البكتير', 'ولعلاج', 'اثار', 'كورو', '٢', 'تيليفاست', 'مضاد', 'الهستام', '٣', 'توبريكس', 'التهاب', 'الملتحم', 'والقرن', 'دكتور', 'تشرحل', 'ليش', 'رقم', '١']

 Question: انا حصلت عندي ضربة في المرفق وانا اخذ شاور وكانت ضربة قوية ضربت في عمود حديدي " لتعليق المناشف " من بعد ذلك والمرفق انزاح من مكانه ويصدر اصوات طقطقه.
 Processed Question: ['ا', 'حصلت', 'عند', 'ضرب', 'المرفق', 'وا', 'اخذ', 'شاور', 'وكانت', 'ضرب', 'قو', 'ضربت', 'عمود', 'حديد', 'لتعليق', 'المناشف', 'والمرفق', 'انزاح', 'مكان', 'ويصدر', 'اصو', 'طقطق']

 Question: مشكلة لدى والدي عمره ٥٩ سنة - يوجد عنده خشونه في الركبة و التهاب يعاني الان من الاآم في الركبة و يوجد تخشب في الاطراف مع العلم يعاني من مرض السكر
 Processed Question: ['مشكل', 'والد', 'عمر', '٥٩', 'سن', 'يوجد', 'عند', 'خشون', 'الركب', 'التهاب', 'يعان', 'ال', 'الاام', 'الركب', 'يوجد', 'تخشب', 'الاطراف', 'العلم', 'يعان', 'مرض', 'السكر']

 Question: السلام عليكم ابنتي حفرة قدمها مائل قليلا الطبيب شك انه خلع ولاده وصورت اليوم تصوير تلفزيوني
 Processed Question: ['السلام', 'علي', 'ابنت', 'حفر', 'قدم', 'مايل', 'قليل', 'الطبيب', 'شك', 'ان', 'خلع', 'ولاد', 'وصورت', 'اليوم', 'تصوير', 'تلفزيون']

 Question: السلام عليكم دكتور هذا حال اظافر رجلي بالذات الظفر الكبير قبل طلعلي ظفر غائر وعانيت وعالجت بعدها عرفت كيف اقص اظافري من بعدها صارت اظافري كذا لست اعلم
 Processed Question: ['السلام', 'علي', 'دكتور', 'حال', 'اظافر', 'رجل', 'بالذ', 'الظفر', 'الكبير', 'طلعل', 'ظفر', 'غاير', 'وعانيت', 'وعالجت', 'بعد', 'عرفت', 'اقص', 'اظافر', 'بعد', 'صارت', 'اظافر', 'اعلم']

 Question: ابني عنيف في بعض الاحيان ومشاغب و بيعمل سلوكيات خاطئه
 Processed Question: ['ابن', 'عنيف', 'الاحي', 'ومشاغب', 'بيعمل', 'سلوكي', 'خاط']

 Question: ظهري يؤلمني من لوح الكتف وبينزل الوجع لتحت
 Processed Question: ['ظهر', 'يولمن', 'لوح', 'الكتف', 'وبينزل', 'الوجع', 'لتحت']

 Question: مشكله بروز الفك العلوي
 Processed Question: ['مشكل', 'بروز', 'الفك', 'العلو']

 Question: السلام عليكم انا عندي تقوس في الرجل وش الحل ؟
 Processed Question: ['السلام', 'علي', 'ا', 'عند', 'تقوس', 'الرجل', 'وش', 'الحل']

 Question: ابني عمره ٨ سنوات عنده شعور الرغبه بأكل شعر الرأس لاكنه لايفعل وسبب له توتر
 Processed Question: ['ابن', 'عمر', '٨', 'سنو', 'عند', 'شعور', 'الرغب', 'باكل', 'شعر', 'الراس', 'لاكن', 'لايفعل', 'وسبب', 'توتر']

 Question: عن العظام
 Processed Question: ['العظام']

 Question: تمنيل اطرافي
 Processed Question: ['تمنيل', 'اطراف']

 Question: في حاجه دخلت عيني او جرحتها بالغلط وهي مره قاعده تعورني مو قادره افتحها
 Processed Question: ['حاج', 'دخلت', 'عين', 'او', 'جرحت', 'بالغلط', 'وه', 'مر', 'قاعد', 'تعورن', 'مو', 'قادر', 'افتح']

 Question: بعاني من النحافه وأخذت ترياكتين لمده ٣ ايام وبعدين بطلت ورجعت بعد شهرين اخدت عشرين يوم مواصلين وبعدين بطلت تاني اخدت شوكلاته لزياده الحديد ومفيش فايد
 Processed Question: ['بعان', 'النحاف', 'واخذت', 'ترياكت', 'لمد', '٣', 'ايام', 'وبعد', 'بطلت', 'ورجعت', 'شهر', 'اخدت', 'يوم', 'مواصل', 'وبعد', 'بطلت', 'تان', 'اخدت', 'شوكلات', 'لزياد', 'الحديد', 'ومفيش', 'فايد']

 Question: عندي رتباك عند فعل اي شيء امام الآخرين ...مع تحرك الاطراف
 Processed Question: ['عند', 'رتباك', 'فعل', 'ا', 'ش', 'امام', 'الاخر', 'تحرك', 'الاطراف']

 Question: نزعت عصب ونظفت خراج وحطيت حشوه مؤقته وتسبب لي الخراج بتورم شديد وتنمل بالوجه واليوم طلع لي هذا باللثه وش السبب؟؟؟
 Processed Question: ['نزعت', 'عصب', 'ونظفت', 'خراج', 'وحطيت', 'حشو', 'موقت', 'وتسبب', 'الخراج', 'بتورم', 'شديد', 'وتنمل', 'بالوج', 'واليوم', 'طلع', 'باللث', 'وش', 'السبب']

 Question: استشاري عظام
 Processed Question: ['استشار', 'عظام']

 Question: الام الضرس
 Processed Question: ['الام', 'الضرس']

 Question: Tawuniya اشعر بالم شديد في الفك هل يوجد حل مؤقت لتسكين الالم مثل الكمادات مثلا او شي اخر؟
 Processed Question: ['Tawuniya', 'اشعر', 'بالم', 'شديد', 'الفك', 'يوجد', 'حل', 'موقت', 'لتسك', 'الالم', 'الكماد', 'مثل', 'او', 'ش', 'اخر']

 Question: كنت بتكلم عادى مع الصيدليى يوم الخميس دخت ووقعت ومناخيرى وبقى اتفتحوا قسلى الضغط واطى جدا بعد كده الجمعة ورم فى بقى السبت فى مناخيرى الاحد فى عينى
 Processed Question: ['كنت', 'بتكلم', 'عادى', 'الصيدليى', 'يوم', 'الخميس', 'دخت', 'ووقعت', 'ومناخيرى', 'وبقى', 'اتفتحو', 'قسلى', 'الضغط', 'واطى', 'جد', 'كد', 'الجمع', 'ورم', 'فى', 'بقى', 'السبت', 'فى', 'مناخيرى', 'الاحد', 'فى', 'عينى']

 Question: أعاني من مرض في الشبكية وأنا الآم لي أسبوعين تقريبًا صرت أشوف زي النور الابيض المتقطع في جانب عيني ولا أدري ايش هذا النور وايش سببه
 Processed Question: ['اعان', 'مرض', 'الشبك', 'وا', 'الام', 'اسبوع', 'تقريب', 'صرت', 'اشوف', 'ز', 'النور', 'الابيض', 'المتقطع', 'جانب', 'عين', 'ادر', 'ايش', 'النور', 'وايش', 'سبب']

 Question: زوجتي ٣٠ عاما تعاني من الم ف الكتف الايسر وتحت الكتف قليلا من الامام والخلف واحيانا تشعر بسخونة ف نفس المكان ولكن الالم غير مستمر
 Processed Question: ['زوجت', '٣٠', 'عام', 'تعان', 'الم', 'الكتف', 'الايسر', 'وتحت', 'الكتف', 'قليل', 'الامام', 'والخلف', 'واحيا', 'تشعر', 'بسخون', 'المك', 'الالم', 'مستمر']

 Question: عندي الم في رجلي اليمنى من اعلى الفخذ لاخر الساق وقت النوم ويزيد مع البرد لدرجة يمنعني من النوم مستمر الالم من سنين وما احس فيه باقي اليوم
 Processed Question: ['عند', 'الم', 'رجل', 'اليمنى', 'اعلى', 'الفخذ', 'لاخر', 'الساق', 'وقت', 'النوم', 'ويزيد', 'البرد', 'لدرج', 'يمنعن', 'النوم', 'مستمر', 'الالم', 'سن', 'احس', 'باق', 'اليوم']

 Question: مرحبا قدمي تورمت قليلا لانها انصدمت بكرسي حديد
 Processed Question: ['مرحب', 'قدم', 'تورمت', 'قليل', 'لان', 'انصدمت', 'بكرس', 'حديد']

 Question: اعاني من زياده الوزن
 Processed Question: ['اعان', 'زياد', 'الوزن']

 Question: بضغض على اسنانى منذ حوالي اربع ايام
 Processed Question: ['بضغض', 'اسنانى', 'حوال', 'اربع', 'ايام']

 Question: الم في الكعب الرجل
 Processed Question: ['الم', 'الكعب', 'الرجل']

 Question: عملت سحب عصب للاسنان قبل اسبوع لابني والى الان يعاني من الن قوي حتى بغد اخذ المسكن
 Processed Question: ['عملت', 'سحب', 'عصب', 'للاسن', 'اسبوع', 'لابن', 'والى', 'ال', 'يعان', 'الن', 'قو', 'بغد', 'اخذ', 'المسكن']

 Question: ارجوشاكرامساعدتي في تحديد المرض الذي اعاني منه في مفصل الركبه اليسرى خلال الأسبوعين الماضيين  اضافة الى ظهور تورم حول مفصل الركبه ويمتد الى اسفل القدم
 Processed Question: ['ارجوشاكرامساعدت', 'تحديد', 'المرض', 'اعان', 'مفصل', 'الركب', 'اليسرى', 'خلال', 'الاسبوع', 'الماضي', 'اضاف', 'الى', 'ظهور', 'تورم', 'حول', 'مفصل', 'الركب', 'ويمتد', 'الى', 'اسفل', 'القدم']

 Question: خدش بالقرنيه
 Processed Question: ['خدش', 'بالقرن']

 Question: ابه أستشير دكتور مكالمه استشاره عن علاج
 Processed Question: ['اب', 'استشير', 'دكتور', 'مكالم', 'استشار', 'علاج']

 Question: زوجي كان مستمر على ادوية الاكتئاب 3 سنين وتركها فجاءه بعدها بشهرين سائت حالته يشعر بدوخه وكهربا بالراس والم بالعظام واكتئاب وحاول الرجوع شهر وماكان لهامفعول وتركها الان ماهو الحل هل الرجوع لها هو الحل
 Processed Question: ['زوج', 'مستمر', 'ادو', 'الاكتياب', '3', 'سن', 'وترك', 'فجا', 'بعد', 'بشهر', 'سايت', 'حالت', 'يشعر', 'بدوخ', 'وكهرب', 'بالراس', 'والم', 'بالعظام', 'واكتياب', 'وحاول', 'الرجوع', 'شهر', 'وماك', 'لهامفعول', 'وترك', 'ال', 'ماهو', 'الحل', 'الرجوع', 'الحل']

 Question: هل هنالك مخاطر عند استعمال المكمل الغذائي ‏Centrum-سينتروم
 Processed Question: ['مخاطر', 'استعمال', 'المكمل', 'الغذاي', 'Centrum', 'سينتروم']

 Question: مرحبا بنتي عمرها ١٠ شهور ونص ولسى م تحبي بس تزحف واذا وقفتها رجلها اليسرى ترفعها هذي صور الاشعه
 Processed Question: ['مرحب', 'بنت', 'عمر', '١٠', 'شهور', 'ونص', 'ولسى', 'تحب', 'تزحف', 'واذ', 'وقفت', 'رجل', 'اليسرى', 'ترفع', 'صور', 'الاشع']

 Question: زوجتي حامل في الشهر الخامس وبسبب حملها لغرض ما بيدها وبطريقة خاطئة تعرض ذراعها الايسر الى الم شديد لا تستطيع النوم بسبب الالم فما هوا الحل من فضلكم
 Processed Question: ['زوجت', 'حامل', 'الشهر', 'الخامس', 'وبسبب', 'حمل', 'لغرض', 'بيد', 'وبطريق', 'خاط', 'تعرض', 'ذراع', 'الايسر', 'الى', 'الم', 'شديد', 'تستطيع', 'النوم', 'بسبب', 'الالم', 'فم', 'هو', 'الحل', 'فضل']

 Question: الم في الفخد الايمن
 Processed Question: ['الم', 'الفخد', 'الايمن']

 Question: انا اعاني من انتفاضات مفاجاه في جسدي وتشنج بسيط في رقابتي نابعه من صدري وعندما تحدث اشعر بي الم في جسدي ويصعب علي التنفس والحديث لي بضع ثواني ونخز
 Processed Question: ['ا', 'اعان', 'انتفاض', 'مفاجا', 'جسد', 'وتشنج', 'بسيط', 'رقابت', 'نابع', 'صدر', 'وعندم', 'تحدث', 'اشعر', 'الم', 'جسد', 'ويصعب', 'عل', 'التنفس', 'والحديث', 'ثوان', 'ونخز']

 Question: انا ام مرضعة عمر طفلتي تقريبا ثلاث اشهر والان وزني 65 واريد النزول الى وزن 57 كم سعرة حرارية احتاج يوميا وافضل طريقة لصرف سعرات اكثر يوميا
 Processed Question: ['ا', 'ام', 'مرضع', 'عمر', 'طفلت', 'تقريب', 'اشهر', 'وال', 'وزن', '65', 'واريد', 'النزول', 'الى', 'وزن', '57', 'سعر', 'حرار', 'احتاج', 'يومي', 'وافضل', 'طريق', 'لصرف', 'سعر', 'اكثر', 'يومي']

 Question: وزني ٥٩ طولي ١٥٠ ابي رجيم ينقص الوزن
 Processed Question: ['وزن', '٥٩', 'طول', '١٥٠', 'اب', 'رجيم', 'ينقص', 'الوزن']

 Question: شد من الخلف بالراس
 Processed Question: ['شد', 'الخلف', 'بالراس']

 Question: اخوي مهلوس يسمع اصوات ووجود اشخاص حوالينه من كثر سماع الاصوات يبدا يشك ف الكل ويضرب من غير وعي كيف يتم علاجه وهل في ادويه هالحاله؟
 Processed Question: ['اخو', 'مهلوس', 'يسمع', 'اصو', 'ووجود', 'اشخاص', 'حوالين', 'كثر', 'سماع', 'الاصو', 'يبد', 'يشك', 'الكل', 'ويضرب', 'وع', 'يتم', 'علاج', 'وهل', 'ادو', 'هالحال']

 Question: صباح الخير دكتور دكتوره انا تعبانه من اسناني ولثتي لدرجة انه اذني ويديني يعورني .. واحس الم ينبظ
 Processed Question: ['الخير', 'دكتور', 'دكتور', 'ا', 'تعبان', 'اسنان', 'ولثت', 'لدرج', 'ان', 'اذن', 'ويدين', 'يعورن', 'واحس', 'الم', 'ينبظ']

 Question: بستشير دكتور
 Processed Question: ['بستشير', 'دكتور']

 Question: السلام عليكم. دورتي متاخره والم بالفخوذ ونغزات وحرقه بالثدي ونفسيه جداً زفت مع افكار سلبيه وسواسس فترة ماقبل الدوره تكون متعبه من الافكار الوسواسيه بس
 Processed Question: ['السلام', 'علي', 'دورت', 'متاخر', 'والم', 'بالفخوذ', 'ونغز', 'وحرق', 'بالثد', 'ونفس', 'جد', 'زفت', 'افكار', 'سلب', 'وسواسس', 'فتر', 'ماقبل', 'الدور', 'تك', 'متعب', 'الافكار', 'الوسواس']

 Question: اعاني من الالم بالاسنان شديد بعد ماشربت عصير بارد اخذت حبوب روفيناك وزاد الالم اخذت المره الان اقدر اخذ شراب فيفادول وكم المقدار اللي اخذه حتى يسكن الالم ؟
 Processed Question: ['اعان', 'الالم', 'بالاسن', 'شديد', 'ماشربت', 'عصير', 'بارد', 'اخذت', 'حبوب', 'روفيناك', 'وزاد', 'الالم', 'اخذت', 'المر', 'ال', 'اقدر', 'اخذ', 'شراب', 'فيفادول', 'و', 'المقدار', 'الل', 'اخذ', 'يسكن', 'الالم']

 Question: اعاني من الدهون والجلد المترهل
 Processed Question: ['اعان', 'الده', 'والجلد', 'المترهل']

 Question: زيادة الوززن
 Processed Question: ['زياد', 'الوززن']

 Question: سمنه و وزني 80
 Processed Question: ['سمن', 'وزن', '80']

 Question: تاءكل في الغضاريف والم أثناء الحركة واسال عاي مدي فاعلية موف فري او كلوكوزامين
 Processed Question: ['تاكل', 'الغضاريف', 'والم', 'الحرك', 'واسال', 'عا', 'مد', 'فاعل', 'موف', 'فر', 'او', 'كلوكوزام']

 Question: اعاني الام فوق عيني اليمنى
 Processed Question: ['اعان', 'الام', 'عين', 'اليمنى']

 Question: دكتور عيون
 Processed Question: ['دكتور', 'عي']

 Question: وجود حبه في العين في الجفن العلوي من الداخل.
 Processed Question: ['وجود', 'حب', 'الع', 'الجفن', 'العلو', 'الداخل']

 Question: السلام عليكم انا عندي احد الاسنان الاماميه مكسوره ولما رحت للدكتور قال محتاج خلع ماهو افضل للسن البديل
 Processed Question: ['السلام', 'علي', 'ا', 'عند', 'احد', 'الاسن', 'الامام', 'مكسور', 'ولم', 'رحت', 'للدكتور', 'قال', 'محتاج', 'خلع', 'ماهو', 'افضل', 'للسن', 'البديل']

 Question: اعاني من الم الاسنان مستمر من ٣ ايام و ذهبت للدكتور و قالي ان في جيوب في اللثه هل جيوب اللثه تسبب هذا الالم
 Processed Question: ['اعان', 'الم', 'الاسن', 'مستمر', '٣', 'ايام', 'ذهبت', 'للدكتور', 'قال', '', 'جيوب', 'اللث', 'جيوب', 'اللث', 'تسبب', 'الالم']

 Question: عندي انتفاخ في جفن العبن اليمنى العلوي في مع حراره بسيطه في طرف العين من الداخل
 Processed Question: ['عند', 'انتفاخ', 'جفن', 'العبن', 'اليمنى', 'العلو', 'حرار', 'بسيط', 'طرف', 'الع', 'الداخل']

 Question: حضرتك انا كنت بعاني من حساسية في العين مع الشعور بوجود رمل في العين واحمرار
 Processed Question: ['حضرتك', 'ا', 'كنت', 'بعان', 'حساس', 'الع', 'الشعور', 'بوجود', 'رمل', 'الع', 'واحمرار']

 Question: ضيق نفس مع خفقان قلب مع دوخه يذهب ويعود من شهر .. ما المشكلة
 Processed Question: ['ضيق', 'خفق', 'قلب', 'دوخ', 'يذهب', 'ويعود', 'شهر', 'المشكل']

 Question: ابني 9 س لدية نزيف باحدى عينه و انفصال شبكي كلي عملنا ليزر لتثبيت الشبكية و النزيف قل يستخدم قطرلت كورتيزون كل ساعتين و مضاد حيوي لكن الالتهاب لا يزول
 Processed Question: ['ابن', '9', 'لد', 'نزيف', 'باحدى', 'عين', 'انفصال', 'شبك', 'كل', 'عمل', 'ليزر', 'لتثبيت', 'الشبك', 'النزيف', 'قل', 'يستخدم', 'قطرلت', 'كورتيز', 'ساعت', 'مضاد', 'حيو', 'الالتهاب', 'يزول']

 Question: neck pain for over 2 weeks now, and today I cannot move my neck
 Processed Question: ['neck', 'pain', 'for', 'over', '2', 'weeks', 'now', 'and', 'today', 'I', 'can', 'not', 'move', 'my', 'neck']

 Question: السلام عليكم
 Processed Question: ['السلام', 'علي']

 Question: تساقط الشعر
 Processed Question: ['تساقط', 'الشعر']

 Question:  Mild spondylodegenerative changes of the dorsal spine with reduced bright T2 signal of the dorsal discs and marginal osteophytosis رجل 33 عام ما التشخيص والعلاج؟
 Processed Question: ['Mild', 'spondylodegenerative', 'changes', 'of', 'the', 'dorsal', 'spine', 'with', 'reduced', 'bright', 'T2', 'signal', 'of', 'the', 'dorsal', 'discs', 'and', 'marginal', 'osteophytosis', 'رجل', '33', 'عام', 'التشخيص', 'والعلاج']

 Question: السمنه المفرطه
 Processed Question: ['السمن', 'المفرط']

 Question: الم في الضرس واعاني من خروج دم من نفس الضرس
 Processed Question: ['الم', 'الضرس', 'واعان', 'خروج', 'دم', 'الضرس']

best preprocessing was using camel tools

In [ ]:
#saving the data to use it neural models notebook
data_dic = {
    'x': [' '.join(tokens) for tokens in preprocessed_Question_camel],
    'y': df['specialty_id'].values}
preprocessed_df = pd.DataFrame(data_dic)

In [ ]:
preprocessed_df.shape

(25000, 2)

In [ ]:
preprocessed_df.to_csv('ready_data.csv', index=False)

#**testing different word representation on logistic regression to know which word representation we should use for the rest**

**Traditional word representation:**

First we have to join the text because the input should be joined i choose camel tools for preprocessing

In [ ]:
join_questions_camel = [' '.join(word) for word in preprocessed_Question_camel]

**BOW Bag of words**

In [ ]:
BOW = CountVectorizer()

***BOW - Bag Of Word with  (camel)***

In [ ]:
BOW_representation = BOW.fit_transform(join_questions_camel)

***splitting***

In [ ]:
X_train_BOW_camel, X_test_BOW_camel, y_train_BOW_camel, y_test_BOW_camel = train_test_split(BOW_representation,df['specialty_id'][:BOW_representation.shape[0]], test_size=0.2 , random_state=42)

**TF_IDF**

In [ ]:
TF_IDF = TfidfVectorizer()

In [ ]:
TF_IDF_representation = TF_IDF.fit_transform(join_questions_camel)

***splitting***

In [ ]:
X_train_TFIDF_camel, X_test_TFIDF_camel, y_train_TFIDF_camel, y_test_TFIDF_camel = train_test_split(TF_IDF_representation, df['specialty_id'][:TF_IDF_representation.shape[0]], test_size=0.2 , random_state=42)

***Logistic Regression - BOW***

In [ ]:
LR_BOW = LogisticRegression()
LR_BOW.fit(X_train_BOW_camel.toarray(), y_train_BOW_camel)
y_pred_LR_BOW = LR_BOW.predict(X_test_BOW_camel.toarray())
print(classification_report(y_test_BOW_camel, y_pred_LR_BOW))

              precision    recall  f1-score   support

          14       0.92      0.87      0.90      1357
          18       0.96      0.90      0.93      1020
          23       0.80      0.83      0.81       810
          25       0.91      0.83      0.87       782
          91       0.75      0.87      0.81      1031

    accuracy                           0.86      5000
   macro avg       0.87      0.86      0.86      5000
weighted avg       0.87      0.86      0.87      5000

***Logistic Regression - TFIDF***

In [ ]:
LR_TFIDF= LogisticRegression()
LR_TFIDF.fit(X_train_TFIDF_camel.toarray(), y_train_TFIDF_camel)
y_pred_LR_TFIDF = LR_TFIDF.predict(X_test_TFIDF_camel.toarray())
print(classification_report(y_test_TFIDF_camel, y_pred_LR_TFIDF))

              precision    recall  f1-score   support

          14       0.92      0.90      0.91      1357
          18       0.97      0.89      0.93      1020
          23       0.83      0.83      0.83       810
          25       0.93      0.83      0.88       782
          91       0.74      0.89      0.81      1031

    accuracy                           0.87      5000
   macro avg       0.88      0.87      0.87      5000
weighted avg       0.88      0.87      0.87      5000

**Non-Traditional word representation**

In [ ]:
#unlike traditional word representation, the model doesnt return a vector to each sentance
#thus we need to take the frequancy of each world by searching it in the model, then take its average to form a vector for each sentance
def average_vec (model, sentance_tokens):
  word_representation = []
  for word in sentance_tokens:
    if word in model.wv:
      word_representation.append(model.wv[word])
    else: #if the word is not found appeand a vec of zeros
      word_representation.append(np.zeros(150))
    #calculating the average
    return np.mean(word_representation, axis=0)

***Word2vec with camel***

In [ ]:
!wget https://archive.org/download/full_grams_cbow_300_twitter/full_uni_cbow_100_twitter.zip
!unzip full_uni_cbow_100_twitter.zip

--2025-06-07 06:32:36--  https://archive.org/download/full_grams_cbow_300_twitter/full_uni_cbow_100_twitter.zip
Resolving archive.org (archive.org)... 207.241.224.2
Connecting to archive.org (archive.org)|207.241.224.2|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://ia802803.us.archive.org/15/items/full_grams_cbow_300_twitter/full_uni_cbow_100_twitter.zip [following]
--2025-06-07 06:32:36--  https://ia802803.us.archive.org/15/items/full_grams_cbow_300_twitter/full_uni_cbow_100_twitter.zip
Resolving ia802803.us.archive.org (ia802803.us.archive.org)... 207.241.232.113
Connecting to ia802803.us.archive.org (ia802803.us.archive.org)|207.241.232.113|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 962251835 (918M) [application/zip]
Saving to: ‘full_uni_cbow_100_twitter.zip’

full_uni_cbow_100_t 100%[===================>] 917.67M  12.9MB/s    in 81s

2025-06-07 06:33:58 (11.3 MB/s) - ‘full_uni_cbow_100_twitter.zip’ saved [962251835/962251835]

Archive:  full_uni_cbow_100_twitter.zip
  inflating: full_uni_cbow_100_twitter.mdl
  inflating: full_uni_cbow_100_twitter.mdl.trainables.syn1neg.npy
  inflating: full_uni_cbow_100_twitter.mdl.wv.vectors.npy

In [ ]:
from gensim.models import Word2Vec
Word2vec= Word2Vec.load("full_uni_cbow_100_twitter.mdl")

In [ ]:
w2v_embeddings =[]
for x in preprocessed_Question_camel:
  v = average_vec(Word2vec, x)
  if v is not None and v.shape == (Word2vec.vector_size,):
    w2v_embeddings.append(v)

word2vec_representation = np.vstack(w2v_embeddings)

In [ ]:
X_train_w2v, X_test_w2v, y_train_w2v, y_test_w2v = train_test_split(word2vec_representation, df['specialty_id'][:len(word2vec_representation)], test_size=0.2 , random_state=42)

***fasttext with camel***

In [ ]:
!wget https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.ar.300.bin.gz

--2025-06-07 06:34:34--  https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.ar.300.bin.gz
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 13.35.37.90, 13.35.37.111, 13.35.37.123, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|13.35.37.90|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4500982519 (4.2G) [application/octet-stream]
Saving to: ‘cc.ar.300.bin.gz’

cc.ar.300.bin.gz    100%[===================>]   4.19G   272MB/s    in 15s

2025-06-07 06:34:49 (281 MB/s) - ‘cc.ar.300.bin.gz’ saved [4500982519/4500982519]

In [ ]:
!gunzip cc.ar.300.bin.gz

In [ ]:
#loading the already pretrained fasttext
Fasttext = fasttext.load_model('cc.ar.300.bin')

In [ ]:
#step 1: unlike traditional word representation, the model doesnt return a vector to each sentance
#thus we need to take the frequancy of each world by searching it in the model, then take its average to form a vector for each sentance

def average_vec_ft(model, sentence_tokens):
    word_representation = []
    for word in sentence_tokens:
        try:
            word_representation.append(model.get_word_vector(word))
        except: #if the word is not found appeand a vec of zeros
            word_representation.append(np.zeros(model.get_dimension()))
    #calculating the average
    return np.mean(word_representation, axis=0) if word_representation else np.zeros(model.get_dimension())

In [ ]:
#averaging the vectors of fasttext
ft_embeddings =[]
for x in preprocessed_Question_camel:
  v = average_vec_ft(Fasttext, x)
  if v is not None and v.shape == (Fasttext.get_dimension(),):
    ft_embeddings.append(v)

In [ ]:
#making sure that only the labels of the valid fasttext embeddings are saved
ft_labels = []
for x,w in enumerate(preprocessed_Question_camel):
  v = average_vec_ft(Fasttext, w)
  if v is not None and v.shape == (Fasttext.get_dimension(),):
    ft_labels.append(df['specialty_id'].iloc[x])

In [ ]:
X_train_ft, X_test_ft, y_train_ft, y_test_ft = train_test_split( np.vstack(ft_embeddings), ft_labels, test_size=0.2, random_state=42)

**Logistic Regression - word2vec**

In [ ]:
LR_w2v = LogisticRegression(max_iter = 1000)
LR_w2v.fit(X_train_w2v, y_train_w2v)
y_pred_LR_w2v = LR_w2v.predict(X_test_w2v)
print(classification_report(y_test_w2v, y_pred_LR_w2v))

              precision    recall  f1-score   support

          14       0.28      0.82      0.41      1138
          18       0.26      0.07      0.11       876
          23       0.11      0.02      0.04       663
          25       0.17      0.01      0.02       637
          91       0.21      0.09      0.12       814

    accuracy                           0.26      4128
   macro avg       0.21      0.20      0.14      4128
weighted avg       0.22      0.26      0.17      4128

**Logistic Regression- FastText**

In [ ]:
LR_FT = LogisticRegression(max_iter = 1000)
LR_FT.fit(X_train_ft, y_train_ft)
y_pred_LR_FT = LR_FT.predict(X_test_ft)
print(classification_report(y_test_ft, y_pred_LR_FT, zero_division=0))

              precision    recall  f1-score   support

          14       0.86      0.87      0.86      1357
          18       0.93      0.86      0.89      1020
          23       0.76      0.74      0.75       810
          25       0.87      0.81      0.84       782
          91       0.73      0.82      0.78      1031

    accuracy                           0.83      5000
   macro avg       0.83      0.82      0.82      5000
weighted avg       0.83      0.83      0.83      5000

# *Best results were using tf-idf*

# **Traditional machine learning models classification**

***Naive Bayes - camel - TFIDF***

In [ ]:
NB_TFIDF = GaussianNB()
NB_TFIDF.fit(X_train_TFIDF_camel.toarray(), y_train_TFIDF_camel)
y_pred_NB_TFIDF = NB_TFIDF.predict(X_test_TFIDF_camel.toarray())
print(classification_report(y_test_TFIDF_camel, y_pred_NB_TFIDF))

              precision    recall  f1-score   support

          14       0.76      0.37      0.50      1357
          18       0.65      0.79      0.71      1020
          23       0.59      0.52      0.55       810
          25       0.36      0.84      0.51       782
          91       0.75      0.43      0.54      1031

    accuracy                           0.56      5000
   macro avg       0.62      0.59      0.56      5000
weighted avg       0.65      0.56      0.56      5000

***Decision Tree - camel - TFIDF***

In [ ]:
DT_TFIDF = DecisionTreeClassifier()
DT_TFIDF.fit(X_train_TFIDF_camel.toarray(), y_train_TFIDF_camel)
y_pred_DT_TFIDF = DT_TFIDF.predict(X_test_TFIDF_camel.toarray())
print(classification_report(y_test_TFIDF_camel, y_pred_DT_TFIDF))

              precision    recall  f1-score   support

          14       0.84      0.84      0.84      1357
          18       0.91      0.87      0.89      1020
          23       0.70      0.76      0.73       810
          25       0.83      0.79      0.81       782
          91       0.73      0.75      0.74      1031

    accuracy                           0.81      5000
   macro avg       0.80      0.80      0.80      5000
weighted avg       0.81      0.81      0.81      5000

***Logistic Regression - TFIDF***

In [ ]:
LR_TFIDF= LogisticRegression()
LR_TFIDF.fit(X_train_TFIDF_camel.toarray(), y_train_TFIDF_camel)
y_pred_LR_TFIDF = LR_TFIDF.predict(X_test_TFIDF_camel.toarray())
print(classification_report(y_test_TFIDF_camel, y_pred_LR_TFIDF))

              precision    recall  f1-score   support

          14       0.92      0.90      0.91      1357
          18       0.97      0.89      0.93      1020
          23       0.83      0.83      0.83       810
          25       0.93      0.83      0.88       782
          91       0.74      0.89      0.81      1031

    accuracy                           0.87      5000
   macro avg       0.88      0.87      0.87      5000
weighted avg       0.88      0.87      0.87      5000